import type { BlogPost, ContentBlock } from './blog-posts'

// Spanish originals. The English editions (blog-shanghai-en.ts) use these translationKeys as
// their slugs, and the translated packs carry them to every other language.
const repo = 'https://github.com/j03rul4nd/ifc-viewer-online/blob/main/'
const slugs = ['shanghai-mapa-3d-bim-gis', 'puentes-peatonales-3d-openstreetmap-shanghai', 'estaciones-tren-shanghai-modelo-3d', 'parques-patios-3d-openstreetmap-shanghai']
const p = (text: string): ContentBlock => ({ type: 'p', text })
const h = (text: string): ContentBlock => ({ type: 'h2', text })
const diagram = (name: string, alt: string): ContentBlock => ({ type: 'image', src: `blog/images/shanghai-${name}.svg`, alt, caption: 'Esquema explicativo, sin escala. No representa dimensiones medidas de Shanghai.', width: 1200, height: 600 })
const related = (index: number): ContentBlock[] => [h('Sigue explorando el caso de Shanghai'), ...slugs.filter((_, i) => i !== index).map(to => ({ type: 'related' as const, to })), { type: 'tool', id: 'viewer', why: 'Abre tu IFC y revisa cómo encaja con su entorno urbano.' }]
const base = { date: '2026-10-03', dateModified: '2026-10-03', lang: 'es', author: 'IFC Viewer Team', category: 'Gemelos digitales', categorySlug: 'digital-twins', readTimeMin: 6 }

export const SHANGHAI_POSTS_ES: BlogPost[] = [
  {
    ...base, slug: slugs[0], translationKey: 'shanghai-city-bim-gis',
    heroImage: 'blog/images/shanghai-bridge-blender-review.jpg',
    heroAlt: 'Render de revisión del anillo de Mingzhu: reconstrucción aproximada sobre cartografía OSM',
    heroCredit: 'IFC Viewer Online · render Blender aproximado · © OpenStreetMap contributors (ODbL)',
    title: 'Shanghai en 3D: cómo combinar edificios IFC y contexto urbano sin perder la realidad',
    seoTitle: 'Shanghai en 3D: edificios IFC y contexto BIM/GIS',
    excerpt: 'De la Perla Oriental a los jardines de Yuyuan: cómo construimos un contexto 3D que conserva calles, accesos y espacios abiertos, y qué límites tiene para un proyecto BIM.',
    seoDescription: 'Explora Shanghai en 3D con IFC y OpenStreetMap. Distingue el modelo BIM, el contexto urbano y las aproximaciones con una demo y ejemplos prácticos.',
    keywords: ['Shanghai 3D', 'mapa 3D Shanghai', 'BIM GIS', 'IFC OpenStreetMap', 'Perla Oriental IFC'],
    references: [
      { id: 'case', title: 'Shanghai: criterios de fidelidad del contexto urbano', source: 'IFC Viewer Online', url: repo + 'docs/SHANGHAI_CITY_FIDELITY.md' },
      { id: 'model', title: 'Perla Oriental: fuentes y límites de la reconstrucción IFC', source: 'IFC Viewer Online', url: repo + 'docs/ORIENTAL_PEARL_RECONSTRUCTION.md' },
    ],
    faqs: [
      { q: '¿Es un gemelo digital de toda Shanghai?', a: 'No. Es una visualización BIM/GIS con reconstrucciones IFC y contexto cartográfico. No implica cobertura completa ni conexión a sensores o datos operativos en tiempo real.' },
      { q: '¿La demo es el IFC original de la Perla Oriental?', a: 'No. Es una reconstrucción aproximada de IFC Viewer Online, con sus fuentes y limitaciones documentadas; no es un modelo conforme a obra.' },
      { q: '¿Puedo usar el mapa para comprobar distancias de obra?', a: 'La escena ilustrativa no basta. Primero hay que validar coordenadas, cotas, procedencia y tolerancias contra puntos de control.' },
    ],
    content: [
      p('Un mapa 3D útil no se limita a colocar edificios sobre una imagen aérea. Debe explicar qué conecta con qué, qué pasa por encima y qué espacios permanecen abiertos. Shanghai nos permitió poner a prueba esas relaciones: puentes peatonales en Lujiazui, grandes estaciones y jardines históricos dentro de una ciudad densa.'),
      { type: 'takeaways', items: ['El IFC aporta elementos del edificio; la cartografía aporta contexto. Sus precisiones no son intercambiables.', 'La continuidad de accesos, vías y patios importa más que añadir detalle decorativo.', 'Puedes inspeccionar una reconstrucción IFC de la Perla Oriental y revisar qué información contiene.'] },
      diagram('capas', 'Tres capas separadas: edificio IFC, cartografía urbana y detalle visual aproximado'),
      h('Qué representa realmente nuestro Shanghai en 3D'),
      p('Un modelo IFC organiza elementos y propiedades del edificio. El mapa sitúa calles, agua, parques e infraestructura alrededor. Combinarlos ayuda a explicar una entrada, el encaje de un volumen o su relación con el espacio público. La condición es que compartan una colocación coherente y que el lector conozca la procedencia de cada capa.'),
      { type: 'table', headers: ['Capa', 'Qué aporta', 'Qué no acredita'], rows: [['IFC', 'Elementos y propiedades del archivo', 'Que sea un modelo conforme a obra'], ['Cartografía OSM', 'Huellas y etiquetas disponibles', 'Cobertura completa o precisión topográfica'], ['Geometría procedural', 'Volumen y detalle para visualizar', 'Mediciones de elementos no documentados']] },
      p('En este caso usamos reconstrucciones IFC de hitos y contexto cartográfico. No ofrecemos un levantamiento completo de Shanghai ni una conexión con su operación diaria. Esta distinción permite utilizar la escena para comunicación y revisión visual sin atribuirle una exactitud que sus fuentes no aportan.'),
      h('Comprueba la colocación antes de añadir detalle'),
      p('Si todo el contexto aparece desplazado varias calles, revisa el sistema de coordenadas antes de mover edificios individualmente. Después comprueba orientación y escala con elementos reconocibles. Finalmente compara cotas: apoyar el IFC y el mapa sobre referencias verticales distintas puede hacer que un acceso flote aunque la planta parezca correcta.'),
      { type: 'p', text: ['Para configurar tu propio archivo, consulta la ', { text: 'guía de IFC georreferenciado sobre un mapa 3D', to: 'ver-ifc-mapa-3d-online' }, '. Aquí nos centramos en la calidad del contexto de Shanghai, no en repetir el procedimiento de georreferenciación.'] },
      h('Tres errores que Shanghai nos obligó a resolver'),
      p('En Lujiazui, el puente no termina en el borde de su tablero: también importan escaleras, ascensores y descansillos. En las estaciones, extruir el vestíbulo como un bloque macizo puede tapar las vías. En Yuyuan, rellenar todos los polígonos elimina patios e islas y cambia la lectura del jardín.'),
      p('El aprendizaje común fue conservar relaciones. Una carretera puede seguir siendo carretera mientras un puente la soporta. Un parque puede contener un hueco. Una cubierta puede proteger un espacio abierto. Las texturas no resuelven estos problemas: primero debe funcionar la organización de la geometría.'),
      { type: 'p', text: ['Los criterios y las limitaciones del trabajo están documentados en nuestro caso de Shanghai. ', { cite: 'case' }] },
      h('Explora la Perla Oriental: del objeto al contexto'),
      { type: 'ifc-demo', modelId: 'oriental-pearl-tower', title: 'Perla Oriental: reconstrucción IFC4', description: 'Modelo aproximado, no conforme a obra. Esta demo muestra el edificio; para revisar el contexto urbano, abre el visor completo y activa el mapa.', schema: 'IFC4', size: '21.2 MB', height: 440 },
      { type: 'steps', items: [{ title: 'Inspecciona los grandes volúmenes', body: 'Carga la demo y compara su silueta desde varios ángulos antes de acercarte a los detalles.' }, { title: 'Consulta elementos y propiedades', body: 'Selecciona piezas del IFC. Diferencia información del archivo de la geometría cartográfica que aparecerá en el mapa.' }, { title: 'Revisa la relación con la calle', body: 'En el visor completo, carga la misma demo desde la galería y activa Map mode. Compara una vista aérea con otra cercana al suelo.' }] },
      { type: 'p', text: ['El archivo es nuestra reconstrucción; no procede del modelo original del edificio. Sus fuentes y decisiones se describen aquí. ', { cite: 'model' }] },
      h('Cómo presentar una revisión sin exagerar su precisión'),
      p('Prepara una vista aérea que explique el lugar, otra a la altura de la calle y un acercamiento a la conexión que quieras discutir. Anota qué pertenece al IFC, qué viene del mapa y qué es aproximado. Si falta una estructura, comprueba la cobertura de los datos: su ausencia en pantalla no demuestra que no exista.'),
      p('Al reutilizar una captura, conserva la atribución cartográfica e indica el carácter aproximado de la reconstrucción. El resultado útil es una decisión espacial más clara. Más edificios o más polígonos en pantalla no prueban por sí solos mayor fidelidad.'),
      ...related(0),
    ],
  },
  {
    ...base, slug: slugs[1], translationKey: 'shanghai-pedestrian-bridges',
    heroImage: 'blog/images/shanghai-bridge-blender-review.jpg',
    heroAlt: 'Reconstrucción aproximada del anillo peatonal de Mingzhu y sus conexiones, renderizada en Blender',
    heroCredit: 'IFC Viewer Online · render Blender aproximado · © OpenStreetMap contributors (ODbL)',
    title: 'Puentes peatonales de Shanghai en 3D: alturas, escaleras y conexiones que sí encajan',
    seoTitle: 'Puentes peatonales 3D: Shanghai y OpenStreetMap',
    excerpt: 'Un anillo elevado puede parecer perfecto desde arriba y fallar a pie de calle. Así revisamos tableros, ensanchamientos, escaleras y ascensores en Lujiazui.',
    seoDescription: 'Cómo representar puentes peatonales de Shanghai: cotas, anchuras, escaleras y ascensores conectados, sin convertir layer de OpenStreetMap en metros.',
    keywords: ['puentes peatonales 3D', 'puentes Shanghai', 'Lujiazui 3D', 'OpenStreetMap layer', 'modelado puentes'],
    references: [{ id: 'case', title: 'Puentes de Lujiazui: reconstrucción, evidencias y límites', source: 'IFC Viewer Online', url: repo + 'docs/SHANGHAI_BRIDGE_RENDERING.md' }, { id: 'layer', title: 'Key:layer — orden vertical de los elementos', source: 'OpenStreetMap', url: 'https://wiki.openstreetmap.org/wiki/Key:layer' }],
    faqs: [{ q: '¿Layer=1 significa un metro de altura?', a: 'No. Layer expresa una relación de orden vertical entre elementos que se cruzan; no es una cota en metros.' }, { q: '¿Una escalera continua demuestra accesibilidad?', a: 'No. La continuidad visual no verifica pendientes, dimensiones, funcionamiento de ascensores ni requisitos de accesibilidad.' }],
    content: [
      p('Un anillo elevado puede parecer correcto desde arriba y fallar al bajar la cámara: escaleras que no llegan al tablero, barandillas atravesando una entrada o una pasarela que se estrecha bruscamente. Por eso revisamos los puentes de Lujiazui como recorridos conectados, no como objetos aislados.'),
      diagram('puentes', 'Sección esquemática de tablero, escalera, descansillo y ascensor con conexiones señaladas'),
      h('La pregunta que revela una mala conexión'),
      p('¿Puedes seguir visualmente el recorrido desde la acera hasta el tablero y desde allí al siguiente acceso? Esta pregunta obliga a mirar los extremos y las uniones. Un puente bonito pero desconectado no explica cómo se recorre el lugar. La comprobación evalúa continuidad del modelo; no certifica la seguridad ni la accesibilidad real.'),
      h('Layer ordena cruces: no mide la altura'),
      { type: 'p', text: ['OpenStreetMap utiliza layer para describir el orden vertical donde se cruzan elementos. No es una elevación métrica. ', { cite: 'layer' }, ' Asignar una altura fija a cada valor puede producir una imagen ordenada, pero no demuestra la altura de un puente concreto.'] },
      p('En nuestro renderizador conservamos por separado la función del recorrido y la estructura que lo soporta. Una vía puede ser peatonal y estar elevada; una carretera puede pasar por un túnel. Cuando faltan medidas, la cota usada para visualizar debe seguir identificada como una aproximación. No basta con que el paso superior quede por encima del inferior.'),
      h('Por qué la anchura debe pertenecer a cada puente'),
      { type: 'image', src: 'blog/images/shanghai-bridge-blender-review.jpg', alt: 'Render en Blender del anillo peatonal de Mingzhu con sus accesos y tablero elevado', caption: 'Geometría del renderizador exportada a Blender para revisar Mingzhu. Entorno oculto para estudiar conexiones; dimensiones y detalles no documentados son aproximados. No es una fotografía.', credit: 'IFC Viewer Online · datos © OpenStreetMap contributors (ODbL)', width: 1400, height: 1000 },
      p('Una pasarela estrecha, una plataforma y un anillo de distribución no tienen la misma sección. Mingzhu nos llevó a aplicar una corrección vinculada a la identidad del puente, en lugar de ensanchar todos los caminos peatonales de Shanghai. Ese límite evita propagar una decisión local al resto de la ciudad.'),
      p('En una unión revisa ambos bordes además del eje. Dos ejes conectados pueden dejar un hueco entre superficies, un solape o una esquina excesivamente aguda. Los cambios de anchura necesitan una transición geométrica que se vea coherente tanto desde arriba como desde la calle. Una barandilla continua también debe interrumpirse donde entra otro recorrido.'),
      h('Escaleras, ascensores y descansillos'),
      p('Una escalera tiene dos extremos con cotas distintas. Su trazado debe desembocar en una superficie de llegada. Para un ascensor, la ubicación cartográfica no describe automáticamente puertas, cabina, cerramiento ni todas sus paradas. Usamos los accesos documentados para situar las conexiones y dejamos aproximados los detalles sin dimensiones.'),
      p('Colocar una torre de ascensor donde resulta estéticamente conveniente añadiría una afirmación sobre el lugar que los datos no sostienen. Lo mismo ocurre con una escalera que desaparece dentro de un edificio: puede existir una conexión interior, pero su geometría no se deduce de una vista exterior. Registra esa ausencia como una cuestión pendiente.'),
      { type: 'table', headers: ['Síntoma', 'Revisar primero', 'Evitar'], rows: [['Acceso flotante', 'Cotas de ambos extremos', 'Mover todo el puente a ojo'], ['Unión estrecha', 'Anchuras y bordes del tablero', 'Conectar únicamente los ejes'], ['Ascensor genérico', 'Ubicación y niveles documentados', 'Inventar paradas'], ['Barandilla en una entrada', 'Abertura y descansillo', 'Cerrar todo el perímetro']] },
      h('Una secuencia de revisión reutilizable'),
      { type: 'steps', items: [{ title: 'Aísla el puente', body: 'Comprueba el perímetro del tablero y sus encuentros con los recorridos vecinos.' }, { title: 'Activa el entorno', body: 'Añade calles, edificios y terreno para buscar colisiones y diferencias de cota.' }, { title: 'Recorre cada acceso con la cámara', body: 'Míralo desde arriba, lateralmente y a altura peatonal. Una sola vista no es suficiente.' }, { title: 'Guarda la evidencia', body: 'Asocia cada corrección con el identificador cartográfico, la fecha y la fuente; distingue ampliaciones propuestas de estructuras existentes.' }] },
      { type: 'p', text: ['El caso de Lujiazui documenta qué partes siguen datos y cuáles son aproximadas. Esa trazabilidad permite revisar por qué elegimos una forma, además de valorar su aspecto. ', { cite: 'case' }] },
      ...related(1),
    ],
  },
  {
    ...base, slug: slugs[2], translationKey: 'shanghai-railway-stations',
    heroImage: 'blog/images/shanghai-rail-blender-review.jpg',
    heroAlt: 'Render de desarrollo ferroviario de Hongqiao con trenes ilustrativos, no seguimiento real',
    heroCredit: 'IFC Viewer Online · render Blender aproximado · © OpenStreetMap contributors (ODbL)',
    title: 'Estaciones de tren de Shanghai en 3D: vías, andenes y cubiertas sin bloques falsos',
    seoTitle: 'Estaciones de Shanghai en 3D: vías y andenes',
    excerpt: 'Hongqiao y Shanghai South muestran por qué una estación necesita algo más que una huella extruida: espacio libre, cotas coherentes y trenes que sigan la vía.',
    seoDescription: 'Aprende a representar estaciones de Shanghai en 3D: vías, andenes, cubiertas abiertas y trenes sobre curvas. Caso práctico con límites documentados.',
    keywords: ['estaciones Shanghai 3D', 'Hongqiao modelo 3D', 'vías tren 3D', 'andenes OpenStreetMap'],
    references: [{ id: 'case', title: 'Shanghai: geometría ferroviaria y límites de inferencia', source: 'IFC Viewer Online', url: repo + 'docs/SHANGHAI_RAIL_RENDERING.md' }, { id: 'gauge', title: 'Key:gauge — ancho de vía', source: 'OpenStreetMap', url: 'https://wiki.openstreetmap.org/wiki/Key:gauge' }],
    faqs: [{ q: '¿Los trenes muestran posiciones en tiempo real?', a: 'No. Son elementos ilustrativos de la escena, no un servicio de seguimiento ferroviario.' }, { q: '¿Se incluyen estaciones subterráneas completas?', a: 'No. La escena de superficie no reconstruye interiores o intercambiadores subterráneos sin datos específicos.' }, { q: '¿Puede usarse como modelo de ingeniería ferroviaria?', a: 'Es contexto visual. Una entrega de ingeniería requiere geometría, referencias y verificaciones adicionales de vías, gálibos, plataformas y estructuras.' }],
    content: [
      p('El contorno de una estación describe solo una parte del problema. Convertirlo en un bloque que llega al suelo puede cerrar el espacio de las vías o borrar la relación entre vestíbulo y andenes. En Shanghai trabajamos con huellas de edificios, trazados ferroviarios y plataformas como piezas relacionadas.'),
      diagram('estaciones', 'Sección explicativa con cubierta abierta, soportes, andén y dos carriles'),
      h('Una estación no es una única extrusión'),
      p('Hongqiao y Shanghai South sirven para revisar organizaciones espaciales distintas. Sus formas específicas se seleccionan mediante identidad cartográfica y ubicación. Así evitamos que cualquier estación del mundo adopte una silueta de Shanghai por compartir una etiqueta genérica.'),
      p('La huella da una restricción de planta, pero no describe todas las alturas ni la estructura interior. Si faltan secciones o dimensiones, la forma exterior puede aproximarse para ayudar a entender el lugar. El vacío bajo un vestíbulo o una marquesina sigue siendo esencial: cerrarlo cambia la relación con las vías.'),
      h('Construir la vía desde su eje'),
      p('El eje permite seguir el recorrido, pero no equivale al ancho de la plataforma ferroviaria. Los carriles deben conservar una separación coherente y las traviesas repartirse por distancia a lo largo del trazado. Reiniciar su colocación en cada segmento produce acumulaciones y huecos en las curvas.'),
      { type: 'p', text: ['La etiqueta gauge requiere interpretar correctamente sus unidades. ', { cite: 'gauge' }, ' Incluso cuando está presente, no aporta el perfil completo del carril, el drenaje ni la geometría del mecanismo de un desvío. Son datos distintos que no conviene deducir de una sola línea.'] },
      p('En nuestro trabajo separamos esos componentes y reservamos detalles pequeños para la zona cercana de revisión. Es una decisión de representación: a distancia importa poder seguir el corredor; cerca importan el espesor, la separación y la continuidad. El detalle no debe cambiar la posición de la vía.'),
      h('La cota del andén necesita una referencia'),
      p('Una plataforma debe revisarse respecto de la vía a la que sirve. Una altura genérica sobre el terreno puede coincidir por casualidad o generar una diferencia imposible. Cuando faltan datos, la altura de visualización debe declararse como un valor de respaldo; no demuestra que todos los andenes de Shanghai midan lo mismo.'),
      p('Los elementos subterráneos necesitan una decisión explícita. En la escena de superficie omitimos trazados subterráneos; no excavamos una estación imaginaria para mostrarlos. Una vista exterior y una sección de infraestructura responden a preguntas diferentes. Presentarlas con la misma apariencia puede inducir a interpretar una omisión como un error de datos.'),
      h('Cubiertas abiertas y trenes sobre curvas'),
      { type: 'image', src: 'blog/images/shanghai-rail-blender-review.jpg', alt: 'Render de revisión en Blender con tren ilustrativo, carriles y traviesas sobre trazados de Hongqiao', caption: 'Render de desarrollo de nuestra geometría ferroviaria, con edificios ocultos para inspeccionar las vías. Vehículos y soportes aproximados; no es una fotografía ni seguimiento en tiempo real.', credit: 'IFC Viewer Online · datos © OpenStreetMap contributors (ODbL)', width: 1400, height: 1000 },
      p('Una marquesina necesita espacio libre debajo. Preservar ese vacío aporta más que decorar una extrusión cerrada con una textura metálica. Del mismo modo, un tren debe compartir la cota de la vía y orientar sus coches siguiendo el recorrido. Una fila de cajas con un único ángulo falla al entrar en una curva.'),
      { type: 'callout', variant: 'info', title: 'Trenes ilustrativos', text: 'Los vehículos de esta escena dan escala y contexto. No representan posiciones operativas ni certifican una réplica de una serie concreta de tren.' },
      { type: 'table', headers: ['Elemento', 'Relación clave', 'Dato necesario para ingeniería'], rows: [['Carriles', 'Separación y alineación', 'Sección y geometría detalladas'], ['Andén', 'Cota respecto de la vía', 'Referencia vertical validada'], ['Cubierta', 'Espacio libre inferior', 'Estructura y apoyos medidos'], ['Tren ilustrativo', 'Recorrido y cota compartidos', 'Flota y posición operativa']] },
      h('Qué revisar antes de compartir la escena'),
      p('Oculta temporalmente los edificios y sigue las vías a través de la estación. Busca discontinuidades, saltos de altura, soportes dentro del corredor y plataformas superpuestas. Después activa las cubiertas: comprueba qué queda tapado y qué se entiende desde fuera. Guarda ambas vistas para explicar la organización sin confundir una vista de revisión con la apariencia real del lugar.'),
      { type: 'p', text: ['Interiores, instalaciones, mecanismos de agujas y gálibos certificados necesitan otras fuentes. Nuestra documentación recoge las aproximaciones de cubiertas, plataformas y vehículos para mantener esa frontera visible. ', { cite: 'case' }] },
      ...related(2),
    ],
  },
  {
    ...base, slug: slugs[3], translationKey: 'shanghai-parks-courtyards',
    heroImage: 'blog/images/shanghai-yuyuan-blender-review.jpg',
    heroAlt: 'Reconstrucción cartográfica aproximada de Yuyuan revisada en Blender',
    heroCredit: 'IFC Viewer Online · render Blender aproximado · © OpenStreetMap contributors (ODbL)',
    title: 'Parques y patios en mapas 3D: lo que aprendimos de Yuyuan y Jing’an',
    seoTitle: 'Parques 3D con OpenStreetMap: Yuyuan y Jing’an',
    excerpt: 'Árboles dentro de plazas, agua sobre islas y patios cubiertos: tres errores que empeoran un mapa aunque tenga mucho detalle. Cómo los abordamos en Shanghai.',
    seoDescription: 'Evita árboles en plazas, agua sobre islas y patios tapados. El caso de Yuyuan y Jing’an para mejorar parques y edificios históricos en mapas 3D.',
    keywords: ['parques 3D OpenStreetMap', 'Yuyuan 3D', 'Jingan modelo 3D', 'patios multipolígonos', 'renderizado urbano'],
    references: [{ id: 'case', title: 'Parques de Shanghai: topología, evidencias y límites', source: 'IFC Viewer Online', url: repo + 'docs/SHANGHAI_PARK_RENDERING.md' }, { id: 'rings', title: 'Relaciones multipolígono y anillos interiores', source: 'OpenStreetMap', url: 'https://wiki.openstreetmap.org/wiki/Relation:multipolygon' }, { id: 'garden', title: 'Visit Shanghai’s classical gardens', source: 'Gobierno municipal de Shanghai', url: 'https://english.shanghai.gov.cn/en-Parks/20241118/3ab0a509201343a59102f9bc63a3aab4.html' }],
    faqs: [{ q: '¿Más árboles hacen un parque 3D más realista?', a: 'No necesariamente. Primero deben respetarse caminos, plazas, agua y huecos; la densidad sin datos sigue siendo una decisión visual.' }, { q: '¿Las cubiertas reproducen exactamente los templos?', a: 'No. Se conservan huellas y formas cartográficas, pero alturas, pendientes y apoyos sin mediciones siguen siendo aproximados.' }],
    content: [
      p('En un jardín, el espacio entre objetos importa tanto como los objetos. Si el césped tapa un patio o el agua rellena una isla, el lugar deja de leerse correctamente aunque cada árbol tenga miles de polígonos. Yuyuan y Jing’an nos sirvieron para revisar esa estructura espacial.'),
      diagram('patios', 'Comparación entre un polígono relleno incorrectamente y otro que conserva patio, estanque y camino'),
      h('La referencia visual no es un plano de colocación'),
      { type: 'p', text: ['La referencia municipal describe Yuyuan mediante pabellones, estanques, rocallas y arquitectura tradicional. ', { cite: 'garden' }, ' Esa descripción orienta la comparación visual, pero no aporta coordenadas para colocar rocas o inventar pabellones. Para situar las piezas partimos de la cartografía disponible.'] },
      p('La diferencia es práctica: puedes buscar una composición más fiel sin presentar como medido lo que solo es plausible. Una reconstrucción útil hace explícito dónde terminan las huellas conocidas y dónde comienzan las decisiones de representación.'),
      h('Cómo conservar los huecos de un polígono'),
      { type: 'p', text: ['Una superficie puede tener un contorno exterior y varios anillos interiores. ', { cite: 'rings' }, ' El renderizador debe generar triángulos dejando esos interiores abiertos. No basta con guardar el hueco en los datos si luego desaparece al construir la malla.'] },
      p('La regla afecta al césped, al agua y a las cubiertas con patios. El borde de una isla también debe contar como orilla al calcular el aspecto del agua. Medir solo hasta el perímetro exterior hace que el agua junto a una isla se comporte visualmente como el centro del estanque.'),
      h('Vegetación que respeta plazas y recorridos'),
      p('Una plaza peatonal suele ser una superficie, no una línea. Excluir árboles únicamente a lo largo de su perímetro deja libre el borde y permite llenar de vegetación el centro. La distribución procedural debe consultar el área pavimentada completa, además de edificios, agua y corredores ferroviarios.'),
      p('Los huecos también deben conservarse al sembrar árboles y arbustos. Corregir el césped y dejar intacto el generador de vegetación produce un patio abierto con troncos dentro. Revisamos ambos procesos por separado porque comparten datos, pero construyen geometrías distintas.'),
      h('Fuentes y mobiliario sin inventar el jardín'),
      p('El promedio de los vértices de una fuente cóncava puede caer fuera de su vaso. Para situar un símbolo de chorros necesitas un punto interior y un tamaño limitado por el borde más cercano. La distancia a un vértice no basta: una arista puede pasar mucho más cerca del punto elegido.'),
      p('Retiramos las pérgolas generadas al azar y restringimos el mobiliario de suelo a recorridos adecuados. Una posición visualmente creíble no es una posición documentada. Conviene distinguir la vegetación ilustrativa de las estructuras que la cartografía identifica expresamente, sobre todo cuando una captura se muestra fuera del visor.'),
      h('Templos: modelar edificios, no todo el recinto'),
      { type: 'image', src: 'blog/images/shanghai-yuyuan-blender-review.jpg', alt: 'Render de revisión en Blender del entorno de Yuyuan con edificios, estanques, caminos y vegetación', caption: 'Revisión geométrica de Yuyuan durante el desarrollo. Huellas cartográficas, alturas no documentadas y vegetación aproximadas. Los materiales de Blender no reproducen los sombreadores del visor.', credit: 'IFC Viewer Online · datos © OpenStreetMap contributors (ODbL)', width: 1400, height: 1000 },
      p('Un recinto religioso puede contener varios edificios y espacios abiertos. Extruir su límite como un solo volumen borra los patios. En Jing’an comprobamos por separado el recinto y la huella del salón principal; en Yuyuan conservamos formas de cubierta etiquetadas que antes se aplanaban.'),
      p('Esto mejora la lectura del conjunto, pero no reconstruye aleros, ornamentación o apoyos exactos. Una marquesina documentada como cubierta abierta necesita vacío debajo. Un templo, una mezquita y un edificio comercial requieren criterios distintos: estar en Shanghai no justifica aplicarles una misma forma.'),
      { type: 'table', headers: ['Error visible', 'Causa probable', 'Comprobación'], rows: [['Agua sobre una isla', 'Anillo interior perdido', 'Triángulos y orillas interiores'], ['Árboles en una plaza', 'Solo se excluyó el perímetro', 'Área pavimentada completa'], ['Fuente fuera del vaso', 'Centro calculado como promedio', 'Punto interior y distancia al borde'], ['Templo como bloque', 'Recinto confundido con edificio', 'Huellas individuales y patios']] },
      h('Una prueba que puedes repetir en cualquier parque'),
      p('Revisa primero el lugar sin árboles: identifica patios, agua, plazas y edificios. Activa la vegetación y comprueba qué espacios invade. Añade el mobiliario al final. Si una capa empeora la lectura de las anteriores, investiga sus exclusiones antes de aumentar el detalle.'),
      { type: 'p', text: ['Guarda vistas cercanas y lejanas. Las primeras revelan colisiones; las segundas muestran si se conserva la organización del lugar. Las fuentes y límites del caso están documentados para que una imagen atractiva no se confunda con un levantamiento. ', { cite: 'case' }] },
      ...related(3),
    ],
  },
]

// Keep FAQ answers visible to readers as well as in the generated structured data.
for (const post of SHANGHAI_POSTS_ES) {
  const at = post.content.findIndex(block => block.type === 'h2' && block.text === 'Sigue explorando el caso de Shanghai')
  post.content.splice(at, 0, h('Preguntas frecuentes'), ...(post.faqs ?? []).flatMap(faq => [
    { type: 'h3' as const, text: faq.q }, p(faq.a),
  ]))
}
