// ─── delivery-report.test.ts ──────────────────────────────────────────────────
// Smoke tests for the F5-02 composer now that it is wired into the export
// modal: verdict selection, fix-first ordering, honesty banner, and escaping
// of the one user-controlled string (the file name).

import { describe, it, expect } from 'vitest'
import { buildDeliveryReportHtml, type DeliveryReportStrings } from './delivery-report'
import type { ValidationIssue } from '../types'

const STRINGS: DeliveryReportStrings = {
  title: 'Delivery readiness report',
  verdictReject: 'Would be rejected',
  verdictAtRisk: 'At risk',
  verdictReady: 'Ready to deliver',
  scoreLabel: 'Health score',
  profileLabel: 'Profile',
  coverageLabel: '{evaluated} of {total} rules evaluated',
  blockersHeading: 'Blockers',
  warningsHeading: 'Warnings',
  affectsLabel: 'Affects {count} element(s)',
  howToFix: 'How to fix',
  noBlockers: 'No blockers found.',
  coverageNote: 'Some rules were not evaluated.',
  disclaimer: 'Self-check, not an official approval.',
  generatedBy: 'Generated by {app} on {date}',
  toolNames: { revit: 'Revit', archicad: 'Archicad', tekla: 'Tekla Structures', allplan: 'Allplan' },
}

const issue = (ruleId: string, severity: ValidationIssue['severity']): ValidationIssue =>
  ({ id: `${ruleId}-${Math.random()}`, ruleId, severity, message: 'x' } as ValidationIssue)

function build(issues: ValidationIssue[], over: Partial<Parameters<typeof buildDeliveryReportHtml>[0]> = {}) {
  return buildDeliveryReportHtml({
    fileName: 'model.ifc', score: 61, profileName: 'Full', rulesEvaluated: 44, rulesTotal: 44,
    isPartialProfile: false, issues, locale: 'en', strings: STRINGS, appLabel: 'IFC Viewer Online vTEST',
    ...over,
  })
}

describe('buildDeliveryReportHtml', () => {
  it('errors → reject verdict; warnings only → at-risk; clean → ready', () => {
    expect(build([issue('duplicate-guids', 'error')])).toContain('Would be rejected')
    expect(build([issue('duplicate-guids', 'warning')])).toContain('At risk')
    expect(build([])).toContain('Ready to deliver')
  })

  it('shows coverage honesty banner only for partial profiles', () => {
    expect(build([], { rulesEvaluated: 10, isPartialProfile: true })).toContain('Some rules were not evaluated.')
    expect(build([])).not.toContain('Some rules were not evaluated.')
  })

  it('escapes a hostile file name (the only user-controlled string)', () => {
    const html = build([], { fileName: '<script>alert(1)</script>.ifc' })
    expect(html).not.toContain('<script>alert(1)')
    expect(html).toContain('&lt;script&gt;')
  })

  it('is a self-contained printable document with the disclaimer', () => {
    const html = build([issue('duplicate-guids', 'error')])
    expect(html).toContain('<!doctype html>')
    expect(html).toContain('Self-check, not an official approval.')
    expect(html).toContain('IFC Viewer Online vTEST')
  })
})
