// ─── Delivery report composer (F5-02) ────────────────────────────────────────
// Composes a ValidationResult into a plain-language, remediation-first
// "would this delivery be rejected, and in what order do I fix it?" one-pager,
// as a self-contained printable HTML document.
//
// 100% client-side, ZERO network: it only reads data the app already holds
// (the ValidationResult + the deterministic D-22 remediation corpus). No IFC
// bytes, no filenames, no element data cross any boundary — nothing is sent
// anywhere; the HTML is handed straight to a Blob download.
//
// Purpose (moat #2 — the retention hook): turn the rule table into delivery
// language — what gets this rejected, ordered by impact, with the exact
// authoring-tool steps to fix it — reusing getRuleRemediation() so the prose
// is deterministic, never generated (D-22).
//
// Honesty (docs-planning/vision/08 §2): the report always states how many rules
// were evaluated under which profile, is explicitly a self-check ("run this
// before your client does"), and never claims an official/approved pass.
//
// Purity: this module threads `locale` (for the locale-aware corpus lookups)
// and a pre-resolved `strings` bag — it never imports react-i18next `t`
// (repo gotcha: never thread `t` into a lib; the component resolves strings).

import { getRuleLabel, type ValidationIssue } from '../types'
import { getRuleRemediation, AUTHORING_TOOLS, type AuthoringTool } from '../i18n/rule-remediation'

/** Localised section labels, resolved by the caller from its i18n hook. */
export interface DeliveryReportStrings {
  /** Document title, e.g. "Delivery readiness report". */
  title: string
  /** Verdict when there are error-severity issues, e.g. "Would be rejected". */
  verdictReject: string
  /** Verdict when only warnings remain, e.g. "At risk — review before delivery". */
  verdictAtRisk: string
  /** Verdict when clean, e.g. "Ready to deliver". */
  verdictReady: string
  /** "Health score" label. */
  scoreLabel: string
  /** "Profile" label. */
  profileLabel: string
  /** "{evaluated} of {total} rules evaluated" — use {evaluated}/{total} placeholders. */
  coverageLabel: string
  /** Heading for the must-fix (errors) section. */
  blockersHeading: string
  /** Heading for the warnings section. */
  warningsHeading: string
  /** Sub-label showing how many elements a rule affects, uses {count}. */
  affectsLabel: string
  /** "How to fix" sub-heading. */
  howToFix: string
  /** Shown when no blockers exist. */
  noBlockers: string
  /** Coverage-honesty note about rules that were not run. */
  coverageNote: string
  /** Footer disclaimer — this is a self-check, not an official pass. */
  disclaimer: string
  /** "Generated by {app} on {date}" — uses {app} and {date}. */
  generatedBy: string
  /** Per-tool display names, keyed by AuthoringTool. */
  toolNames: Record<AuthoringTool, string>
}

export interface DeliveryReportInput {
  fileName: string
  /** 0–100 quality score. */
  score: number
  /** Human-readable profile name (already resolved by the caller). */
  profileName: string
  /** How many rules were actually evaluated (coverage), for honest display. */
  rulesEvaluated: number
  /** Canonical total rule count (RULE_COUNT). */
  rulesTotal: number
  /** True when a partial/custom profile ran — surfaces the honesty banner. */
  isPartialProfile: boolean
  issues: ValidationIssue[]
  /** BCP-47 / two-letter locale for corpus + label lookups. */
  locale: string
  strings: DeliveryReportStrings
  /** App name + version string for the footer. */
  appLabel: string
}

interface RuleGroup {
  ruleId: string
  label: string
  severity: 'error' | 'warning'
  count: number
}

/** Group issues by rule, keep the worst severity per rule, drop info-only. */
function groupByRule(issues: ValidationIssue[], locale: string): RuleGroup[] {
  const map = new Map<string, RuleGroup>()
  for (const i of issues) {
    if (i.severity === 'info') continue
    const existing = map.get(i.ruleId)
    if (existing) {
      existing.count += 1
      if (i.severity === 'error') existing.severity = 'error'
    } else {
      map.set(i.ruleId, {
        ruleId: i.ruleId,
        label: getRuleLabel(i.ruleId, locale),
        severity: i.severity,
        count: 1,
      })
    }
  }
  // Errors first, then by descending count — the fix-first order.
  return [...map.values()].sort((a, b) => {
    if (a.severity !== b.severity) return a.severity === 'error' ? -1 : 1
    return b.count - a.count
  })
}

// ── HTML escaping (the report embeds corpus prose + a user filename) ──────────
const ESC: Record<string, string> = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }
function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ESC[c])
}

function fmt(tpl: string, vars: Record<string, string | number>): string {
  return tpl.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`))
}

function renderRuleBlock(g: RuleGroup, s: DeliveryReportStrings, locale: string): string {
  const rem = getRuleRemediation(g.ruleId, locale)
  const summary = rem?.summary ?? ''
  const toolSteps = rem
    ? AUTHORING_TOOLS
        .filter((tool) => rem.tools[tool])
        .map(
          (tool) =>
            `<li><span class="tool">${esc(s.toolNames[tool])}</span> ${esc(rem.tools[tool] as string)}</li>`,
        )
        .join('')
    : ''
  return `
    <section class="rule ${g.severity}">
      <h3><span class="badge">${g.severity === 'error' ? '✕' : '!'}</span> ${esc(g.label)}</h3>
      <p class="affects">${esc(fmt(s.affectsLabel, { count: g.count }))}</p>
      ${summary ? `<p class="summary">${esc(summary)}</p>` : ''}
      ${toolSteps ? `<p class="howto">${esc(s.howToFix)}</p><ul class="tools">${toolSteps}</ul>` : ''}
    </section>`
}

/**
 * Build the self-contained printable delivery report HTML.
 * Deterministic and pure: same inputs → same bytes (except the footer date).
 */
export function buildDeliveryReportHtml(input: DeliveryReportInput): string {
  const { strings: s, locale } = input
  const groups = groupByRule(input.issues, locale)
  const blockers = groups.filter((g) => g.severity === 'error')
  const warnings = groups.filter((g) => g.severity === 'warning')

  const verdict = blockers.length > 0 ? s.verdictReject : warnings.length > 0 ? s.verdictAtRisk : s.verdictReady
  const verdictClass = blockers.length > 0 ? 'reject' : warnings.length > 0 ? 'atrisk' : 'ready'

  const coverage = fmt(s.coverageLabel, { evaluated: input.rulesEvaluated, total: input.rulesTotal })
  const date = new Date().toISOString().slice(0, 10)

  const blockersHtml = blockers.length
    ? blockers.map((g) => renderRuleBlock(g, s, locale)).join('')
    : `<p class="none">${esc(s.noBlockers)}</p>`
  const warningsHtml = warnings.map((g) => renderRuleBlock(g, s, locale)).join('')

  return `<!doctype html>
<html lang="${esc(locale.split('-')[0])}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(s.title)} — ${esc(input.fileName)}</title>
<style>
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { font: 15px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1a1a1a; background: #fff; margin: 0; padding: 32px; max-width: 820px; margin-inline: auto; }
  header { border-bottom: 2px solid #e3e3e3; padding-bottom: 16px; margin-bottom: 24px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .file { color: #666; font-size: 14px; word-break: break-all; }
  .verdict { display: inline-block; margin-top: 14px; padding: 8px 16px; border-radius: 8px; font-weight: 700; font-size: 16px; }
  .verdict.reject { background: #fdecec; color: #b3261e; }
  .verdict.atrisk { background: #fff4e5; color: #92600a; }
  .verdict.ready { background: #e7f5ea; color: #1a7f37; }
  .meta { display: flex; flex-wrap: wrap; gap: 20px; margin-top: 16px; font-size: 14px; }
  .meta div { display: flex; flex-direction: column; }
  .meta .k { color: #888; font-size: 12px; text-transform: uppercase; letter-spacing: .04em; }
  .meta .v { font-weight: 600; }
  .coverage { margin-top: 12px; font-size: 13px; color: #666; }
  .coverage.partial { padding: 8px 12px; background: #fff4e5; border-left: 3px solid #e0a020; border-radius: 4px; color: #6b4a00; }
  h2 { font-size: 16px; margin: 32px 0 12px; padding-bottom: 6px; border-bottom: 1px solid #eee; }
  .rule { padding: 14px 16px; border-radius: 8px; margin-bottom: 12px; border: 1px solid #eee; }
  .rule.error { background: #fdfafa; border-color: #f3d0cd; }
  .rule.warning { background: #fffdf8; border-color: #f0e2c4; }
  .rule h3 { font-size: 15px; margin: 0 0 4px; display: flex; align-items: center; gap: 8px; }
  .badge { display: inline-flex; align-items: center; justify-content: center; width: 20px; height: 20px; border-radius: 50%; font-size: 12px; font-weight: 700; color: #fff; flex: none; }
  .rule.error .badge { background: #b3261e; }
  .rule.warning .badge { background: #b9860b; }
  .affects { color: #777; font-size: 13px; margin: 0 0 8px; }
  .summary { margin: 0 0 10px; }
  .howto { font-weight: 600; font-size: 13px; margin: 0 0 6px; color: #444; }
  ul.tools { margin: 0; padding-left: 18px; }
  ul.tools li { margin-bottom: 6px; font-size: 13px; }
  ul.tools .tool { font-weight: 700; }
  .none { color: #1a7f37; font-weight: 600; }
  .note { margin-top: 24px; padding: 12px 14px; background: #f6f8fa; border-radius: 8px; font-size: 13px; color: #555; }
  footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
  @media print { body { padding: 0; } .rule { break-inside: avoid; } }
</style>
</head>
<body>
  <header>
    <h1>${esc(s.title)}</h1>
    <div class="file">${esc(input.fileName)}</div>
    <div class="verdict ${verdictClass}">${esc(verdict)}</div>
    <div class="meta">
      <div><span class="k">${esc(s.scoreLabel)}</span><span class="v">${input.score}/100</span></div>
      <div><span class="k">${esc(s.profileLabel)}</span><span class="v">${esc(input.profileName)}</span></div>
    </div>
    <div class="coverage${input.isPartialProfile ? ' partial' : ''}">${esc(coverage)}</div>
  </header>

  <h2>${esc(s.blockersHeading)}</h2>
  ${blockersHtml}

  ${warnings.length ? `<h2>${esc(s.warningsHeading)}</h2>${warningsHtml}` : ''}

  <div class="note">${esc(s.coverageNote)}</div>

  <footer>
    <p>${esc(s.disclaimer)}</p>
    <p>${esc(fmt(s.generatedBy, { app: input.appLabel, date }))}</p>
  </footer>
</body>
</html>`
}
