// ─── barcelona-barris ────────────────────────────────────────────────────────
// Which Barcelona barri / district a lat-lon falls in, and what URBAN TYPOLOGY
// that fabric has — with concrete numbers the OSM scene can render from when a
// building carries no height, colour or roof tags (the common case).
//
// PURE and deterministic. The boundary data is generated by
// scripts/geo/build-barcelona-barris.mjs from OpenStreetMap
// (© OpenStreetMap contributors, ODbL) into barcelona-barris.data.ts.
//
// How a point gets its typology:
//   1. `isBarcelona` — bbox of the municipality, a handful of comparisons, so
//      it can gate every feature of a scene. It is a PREFILTER: the bbox also
//      covers slivers of L'Hospitalet, Esplugues, Montcada and Badalona.
//   2. `barriAt` — bbox-prefiltered point-in-polygon over the 73 barris.
//   3. The barri's typology comes from BARRI_TYPOLOGY (one reviewable row per
//      barri). A few barris straddle two very different fabrics that matter
//      visually (Montjuïc park lies inside el Poble-sec; the Nova Bocana /
//      Hotel W pier inside la Barceloneta), so a short list of hand-drawn
//      TYPOLOGY_ZONES overrides the barri's value inside them.

import { BCN_BARRIS, BCN_BBOX, BCN_DISTRICTS } from './barcelona-barris.data'

// ── Typologies ─────────────────────────────────────────────────────────────────

export const URBAN_TYPOLOGIES = [
  'eixample-cerda',
  'ciutat-vella-medieval',
  'barceloneta',
  'vila-antiga',
  'poblenou-industrial-22a',
  'villa-residential',
  'zona-alta-apartments',
  'poligon-1960s',
  'hillside-selfbuilt',
  'modern-waterfront',
  'hillside-park',
  'port-industrial',
  'mixed-urban',
] as const

/**
 * How Barcelona's fabric actually differs, as a small closed set:
 * - `eixample-cerda` — Cerdà grid: 113 m chamfered blocks, perimeter blocks PB+5 + àtic.
 * - `ciutat-vella-medieval` — Gòtic/Born/Raval: narrow irregular streets, PB+4/5.
 * - `barceloneta` — 1753 grid of long thin blocks of "quarts de casa", PB+4, pastels.
 * - `vila-antiga` — absorbed villages (Gràcia, Sants, Sant Andreu, Sarrià, Horta): PB+2/3.
 * - `poblenou-industrial-22a` — Cerdà grid with brick factories + 22@ offices.
 * - `villa-residential` — Pedralbes, Bonanova, Vallvidrera: detached villas, gardens.
 * - `zona-alta-apartments` — Galvany, Putxet, Tres Torres: upper-class apartment blocks with deep terraces.
 * - `poligon-1960s` — open slab/tower estates (Nou Barris, Besòs, Montbau…), brick, 8–14 floors.
 * - `hillside-selfbuilt` — Carmel, Roquetes, Torre Baró: self-built ("autoconstrucció") small houses on steep slopes.
 * - `modern-waterfront` — Vila Olímpica, Diagonal Mar, Nova Bocana: 1990s–2000s towers.
 * - `hillside-park` — Montjuïc, Park Güell: pavilions and a few buildings in parkland.
 * - `port-industrial` — port / Zona Franca warehouses and sheds.
 * - `mixed-urban` — fallback: dense 20th-century "entre mitgeres" infill, PB+4/6.
 */
export type UrbanTypology = (typeof URBAN_TYPOLOGIES)[number]

/**
 * Barri → typology, keyed by the OSM `name` exactly as in barcelona-barris.data.ts.
 * Every one of the 73 barris has a row (a test enforces it). Where a barri is
 * mixed, the value is the fabric that covers most of its BUILT area.
 */
export const BARRI_TYPOLOGY: Readonly<Record<string, UrbanTypology>> = {
  // ── 1 Ciutat Vella ──
  'el Raval': 'ciutat-vella-medieval', // 18th–19th c. dense arrabal, narrow streets, PB+4/5
  'el Gòtic': 'ciutat-vella-medieval', // Roman/medieval core
  'la Barceloneta': 'barceloneta', // Cermeño's 1753 grid of quarts de casa (Nova Bocana → zone)
  'Sant Pere, Santa Caterina i la Ribera': 'ciutat-vella-medieval', // Born / Ribera medieval fabric
  // ── 2 Eixample — all on Cerdà's 1859 grid ──
  'el Fort Pienc': 'eixample-cerda',
  'la Sagrada Família': 'eixample-cerda',
  "la Dreta de l'Eixample": 'eixample-cerda',
  "l'Antiga Esquerra de l'Eixample": 'eixample-cerda',
  "la Nova Esquerra de l'Eixample": 'eixample-cerda',
  'Sant Antoni': 'eixample-cerda',
  // ── 3 Sants-Montjuïc ──
  'el Poble-sec': 'mixed-urban', // 19th-c. regular grid of narrow streets, PB+3/5 (Montjuïc park → zone)
  'la Marina del Prat Vermell': 'port-industrial', // Zona Franca + port; housing is a small part
  'la Marina de Port': 'poligon-1960s', // 1950s–60s estates (Can Clos, Estadella, Polvorí)
  'la Font de la Guatlla': 'vila-antiga', // low 1920s houses PB+1/2 under Montjuïc
  Hostafrancs: 'vila-antiga', // 19th-c. village grid next to Sants
  'la Bordeta': 'mixed-urban', // old industrial belt re-filled with mid-century blocks
  'Sants-Badal': 'mixed-urban', // dense 1950s–70s entre-mitgeres
  Sants: 'vila-antiga', // old village of Sants along Carrer de Sants
  // ── 4 Les Corts ──
  'les Corts': 'mixed-urban', // village core largely replaced by 1960s–80s blocks
  'la Maternitat i Sant Ramon': 'poligon-1960s', // open blocks around Camp Nou / Maternitat
  Pedralbes: 'villa-residential', // villas, low luxury blocks, gardens
  // ── 5 Sarrià - Sant Gervasi ──
  'Vallvidrera, el Tibidabo i les Planes': 'villa-residential', // villas in Collserola
  Sarrià: 'vila-antiga', // old village of Sarrià (upper fringe villas)
  'les Tres Torres': 'zona-alta-apartments', // upper-class blocks with terraces
  'Sant Gervasi - la Bonanova': 'villa-residential', // torres + low blocks, gardens
  'Sant Gervasi - Galvany': 'zona-alta-apartments', // dense upper-class apartment blocks
  'el Putxet i el Farró': 'zona-alta-apartments', // apartment blocks + remaining torres on a hill
  // ── 6 Gràcia ──
  'Vallcarca i els Penitents': 'mixed-urban', // hillside with 1960s–70s blocks and old houses
  'el Coll': 'hillside-selfbuilt', // self-built hillside barri
  'la Salut': 'vila-antiga', // small houses and low blocks round Park Güell (park → zone)
  'la Vila de Gràcia': 'vila-antiga', // the old village of Gràcia
  "el Camp d'en Grassot i Gràcia Nova": 'eixample-cerda', // mostly Cerdà blocks east of Gràcia
  // ── 7 Horta-Guinardó ──
  'el Baix Guinardó': 'mixed-urban', // dense mid-century blocks above the Eixample
  'Can Baró': 'hillside-selfbuilt', // steep, self-built origins
  'el Guinardó': 'mixed-urban', // garden-city remnants + dense 1960s blocks
  "la Font d'en Fargues": 'villa-residential', // early-20th-c. garden-city of torres
  'el Carmel': 'hillside-selfbuilt', // steep small plots, autoconstrucció + 1960s infill
  'la Teixonera': 'hillside-selfbuilt', // steep self-built hillside
  'Sant Genís dels Agudells': 'poligon-1960s', // 1960s–70s estates on the hillside
  Montbau: 'poligon-1960s', // 1958–61 planned modernist estate
  "la Vall d'Hebron": 'poligon-1960s', // hospital + 1970s blocks + Olympic area
  'la Clota': 'vila-antiga', // tiny rural hamlet of low houses
  Horta: 'vila-antiga', // old village of Horta
  // ── 8 Nou Barris ──
  'Vilapicina i la Torre Llobeta': 'mixed-urban', // dense 1950s–60s entre-mitgeres
  Porta: 'mixed-urban', // mid-century blocks, mixed plots
  'el Turó de la Peira': 'poligon-1960s', // 1950s block estate
  'Can Peguera': 'vila-antiga', // 1929 "cases barates": PB/PB+1 row houses
  'la Guineueta': 'poligon-1960s', // 1960s estate
  Canyelles: 'poligon-1960s', // 1970s estate
  'les Roquetes': 'hillside-selfbuilt', // self-built on the Collserola slope
  Verdun: 'poligon-1960s', // Via Júlia / Patronat estates
  'la Prosperitat': 'poligon-1960s', // Via Júlia blocks
  'la Trinitat Nova': 'poligon-1960s', // 1950s estate
  'Torre Baró': 'hillside-selfbuilt', // self-built detached houses on steep slopes
  'Ciutat Meridiana': 'poligon-1960s', // 1960s–70s towers on the hillside
  Vallbona: 'vila-antiga', // small low-rise settlement by the Rec Comtal
  // ── 9 Sant Andreu ──
  'la Trinitat Vella': 'poligon-1960s', // mid-century blocks
  'Baró de Viver': 'poligon-1960s', // estate that replaced the cases barates
  'el Bon Pastor': 'poligon-1960s', // new blocks replacing cases barates + industry
  'Sant Andreu de Palomar': 'vila-antiga', // old village of Sant Andreu
  'la Sagrera': 'mixed-urban', // village core + dense 20th-c. blocks
  'el Congrés i els Indians': 'mixed-urban', // 1952 Congress estate + low Indians houses
  Navas: 'mixed-urban', // dense mid-century blocks
  // ── 10 Sant Martí ──
  "el Camp de l'Arpa del Clot": 'eixample-cerda', // Cerdà blocks filled mid-century
  'el Clot': 'mixed-urban', // old Clot core + Cerdà blocks
  'el Parc i la Llacuna del Poblenou': 'poblenou-industrial-22a', // 22@ Llacuna
  'la Vila Olímpica del Poblenou': 'modern-waterfront', // 1992 Olympic village
  'el Poblenou': 'poblenou-industrial-22a', // factories, Rambla del Poblenou, 22@
  'Diagonal Mar i el Front Marítim del Poblenou': 'modern-waterfront', // 2000s towers, Fòrum
  'el Besòs i el Maresme': 'poligon-1960s', // Polígon del Besòs (1959–66) + Maresme blocks
  'Provençals del Poblenou': 'poblenou-industrial-22a', // 22@ + factories
  'Sant Martí de Provençals': 'poligon-1960s', // Polígon de Sant Martí dominates the tiny old centre
  'la Verneda i la Pau': 'poligon-1960s', // 1960s–70s estates (La Pau)
}

/**
 * Sub-barri overrides where one barri holds two fabrics that render very
 * differently. Coarse hand-drawn rings, [lat, lon] pairs, tested first.
 * `barris` restricts a zone to points inside those barris (null = any).
 */
export interface TypologyZone {
  readonly id: string
  readonly typology: UrbanTypology
  readonly barris: readonly string[] | null
  readonly ring: readonly (readonly [number, number])[]
}

export const TYPOLOGY_ZONES: readonly TypologyZone[] = [
  {
    // Parc de Montjuïc: castle, MNAC, Anella Olímpica, gardens, cemetery — it is
    // all inside the el Poble-sec barri in OSM (and the official division). The
    // ring hugs the park's edge above Poble-sec and Font de la Guatlla.
    id: 'montjuic-park',
    typology: 'hillside-park',
    barris: null,
    ring: [
      [41.3700, 2.1460], [41.3716, 2.1510], [41.3712, 2.1565], [41.3706, 2.1610],
      [41.3708, 2.1655], [41.3712, 2.1712], [41.3690, 2.1752], [41.3610, 2.1725],
      [41.3555, 2.1650], [41.3505, 2.1560], [41.3515, 2.1470], [41.3610, 2.1450],
    ],
  },
  {
    // Park Güell (la Salut): parkland with a handful of Gaudí-era buildings.
    id: 'park-guell',
    typology: 'hillside-park',
    barris: null,
    ring: [
      [41.4160, 2.1490], [41.4168, 2.1535], [41.4148, 2.1565], [41.4122, 2.1540], [41.4118, 2.1500],
    ],
  },
  {
    // Nova Bocana: the pier south of Plaça del Mar (Hotel W, Sant Sebastià) —
    // 2000s waterfront, not the 18th-c. Barceloneta grid which ends at ~41.3745.
    id: 'nova-bocana',
    typology: 'modern-waterfront',
    barris: ['la Barceloneta'],
    ring: [[41.3735, 2.1840], [41.3735, 2.1970], [41.3600, 2.1970], [41.3600, 2.1840]],
  },
  {
    // North edge of the la Barceloneta barri, beyond the 1753 grid (which ends
    // at Carrer del Doctor Aiguader): Parc de la Barceloneta, Torre Mare
    // Nostrum, Hotel Arts — late-20th-c. waterfront, not quarts de casa.
    id: 'barceloneta-north',
    typology: 'modern-waterfront',
    barris: ['la Barceloneta'],
    ring: [
      [41.3852, 2.1860], [41.3852, 2.1938], [41.3835, 2.1950], [41.3835, 2.2000],
      [41.3900, 2.2000], [41.3900, 2.1860],
    ],
  },
]

// ── Rendering profiles ────────────────────────────────────────────────────────

/** Linear RGB-ish triple in 0..1 (sRGB values; convert as the renderer needs). */
export type RGB = readonly [number, number, number]

export interface TypologyProfile {
  /** Typical storey count range INCLUDING ground floor, and the default when a building has no height/levels. */
  readonly storeys: { readonly min: number; readonly max: number; readonly default: number }
  /** Floor-to-floor height of the ground floor ("planta baixa"), m. */
  readonly groundFloorHeightM: number
  /** Floor-to-floor height of upper storeys, m. */
  readonly upperStoreyHeightM: number
  /** 5–8 realistic facade tones for this fabric. */
  readonly facadePalette: readonly RGB[]
  /** Shutter ("persiana") tone. */
  readonly shutterTone: RGB
  /** Window frame / carpentry tone. */
  readonly windowFrameTone: RGB
  /** Window (or balcony door) width, m. */
  readonly windowWidthM: number
  /** Bay = centre-to-centre window spacing, m. */
  readonly bayM: number
  readonly balcony: { readonly probability: number; readonly depthM: number }
  /** Stepped-back top floor ("àtic"): chance and setback from the facade line. */
  readonly attic: { readonly probability: number; readonly setbackM: number }
  readonly roof: {
    /** Probability a roof is a flat walkable "terrat" rather than pitched. */
    readonly flatTerraceProbability: number
    readonly tones: readonly RGB[]
    /** Parapet ("barana de terrat") height, m. */
    readonly parapetHeightM: number
  }
  /**
   * Cerdà block rule: the built strip is `buildableDepthM` deep from the facade
   * line; deeper than that is the block interior ("interior d'illa"), typically
   * ground floor only at `interiorGroundFloorHeightM`. null outside the grid.
   */
  readonly cerdaBlock: { readonly buildableDepthM: number; readonly interiorGroundFloorHeightM: number } | null
}

// Shared tones. "Verd Barcelona" is the dark green of wooden persianes seen on
// most pre-1970 facades; later estates use aluminium roller shutters.
const VERD_PERSIANA: RGB = [0.24, 0.36, 0.28]
const DARK_WOOD: RGB = [0.30, 0.22, 0.16]
const ALUMINIUM: RGB = [0.70, 0.71, 0.72]
const ROLLER_BEIGE: RGB = [0.66, 0.62, 0.52]
const TERRAT_TILE: RGB = [0.70, 0.50, 0.38] // "rajola de terrat" (red clay tile)
const CEMENT_GREY: RGB = [0.62, 0.61, 0.58]
const ROOF_WHITE: RGB = [0.86, 0.86, 0.84] // waterproofing membranes
const ARAB_TILE: RGB = [0.64, 0.38, 0.28] // "teula àrab" pitched roofs

// Heights: Catalan habitability decree (D. 141/2012) requires 2.5 m clear in
// dwellings → ≥ 2.8 m floor-to-floor; older fabric runs higher. Numbers below
// are typical measured floor-to-floor values, not legal maxima.
export const TYPOLOGY_PROFILES: Readonly<Record<UrbanTypology, TypologyProfile>> = {
  'eixample-cerda': {
    // PGM-76 zone 13b / Ordenança de l'Eixample: 20.75 m cornice on 20 m streets
    // ≈ PB+5, plus a stepped-back àtic (and often a sobreàtic) → 7 levels ≈ 23.7 m.
    // 1960s Porcioles overbuilds reach 8–9 levels.
    storeys: { min: 4, max: 9, default: 7 },
    groundFloorHeightM: 4.5, // tall planta baixa, often with an entresòl
    upperStoreyHeightM: 3.2, // principal ~3.6–4 m, upper floors ~3.0
    facadePalette: [
      [0.78, 0.70, 0.56], // Montjuïc sandstone
      [0.80, 0.64, 0.42], // ochre render
      [0.90, 0.85, 0.74], // cream stucco
      [0.74, 0.73, 0.70], // pale grey stone
      [0.66, 0.42, 0.30], // exposed brick (modernista / 1900s)
      [0.85, 0.68, 0.58], // salmon render
      [0.92, 0.90, 0.86], // white stucco (later rehab)
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: DARK_WOOD,
    windowWidthM: 1.2, // tall balcony doors ~1.1–1.3 m
    bayM: 3.6, // 3–5 bays on a ~15–20 m plot frontage
    balcony: { probability: 0.85, depthM: 0.6 }, // wrought-iron balconies ~0.4–0.8 m
    attic: { probability: 0.7, setbackM: 3 }, // ordinance àtic setback 3 m
    roof: { flatTerraceProbability: 0.95, tones: [TERRAT_TILE, CEMENT_GREY, ROOF_WHITE], parapetHeightM: 1.0 },
    // 1986 Ordenança de rehabilitació i millora de l'Eixample: 28 m buildable
    // depth; the interior may be built at ground floor only (~4.5 m).
    cerdaBlock: { buildableDepthM: 28, interiorGroundFloorHeightM: 4.5 },
  },
  'ciutat-vella-medieval': {
    // PB+4/5 ≈ 15–19 m on narrow 5–8 m plots; Ciutat Vella ordinances cap by street width.
    storeys: { min: 3, max: 7, default: 5 },
    groundFloorHeightM: 4.0,
    upperStoreyHeightM: 3.0,
    facadePalette: [
      [0.78, 0.60, 0.38], // ochre
      [0.72, 0.45, 0.32], // terracotta
      [0.86, 0.76, 0.52], // faded yellow
      [0.82, 0.63, 0.56], // faded pink
      [0.66, 0.63, 0.58], // weathered stone
      [0.88, 0.82, 0.70], // cream
      [0.70, 0.66, 0.58], // grimy render
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: DARK_WOOD,
    windowWidthM: 1.0,
    bayM: 2.8, // two to three bays per narrow plot
    balcony: { probability: 0.9, depthM: 0.45 }, // shallow in narrow streets
    attic: { probability: 0.15, setbackM: 2.5 },
    roof: { flatTerraceProbability: 0.8, tones: [TERRAT_TILE, ARAB_TILE, CEMENT_GREY], parapetHeightM: 0.9 },
    cerdaBlock: null,
  },
  barceloneta: {
    // 1753 houses (8.4 m frontage) raised over time to PB+4 ≈ 14–16 m;
    // subdivided into "quarts de casa" with low ceilings.
    storeys: { min: 3, max: 6, default: 5 },
    groundFloorHeightM: 3.6,
    upperStoreyHeightM: 2.8,
    facadePalette: [
      [0.93, 0.86, 0.62], // pale yellow
      [0.92, 0.72, 0.62], // salmon
      [0.72, 0.80, 0.84], // pale blue
      [0.74, 0.84, 0.74], // mint
      [0.92, 0.88, 0.78], // cream
      [0.90, 0.74, 0.74], // pink
      [0.84, 0.68, 0.46], // ochre
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: DARK_WOOD,
    windowWidthM: 1.0,
    bayM: 2.6,
    balcony: { probability: 0.95, depthM: 0.4 }, // one balcony per window, laundry
    attic: { probability: 0.1, setbackM: 2 },
    roof: { flatTerraceProbability: 0.9, tones: [TERRAT_TILE, CEMENT_GREY, ROOF_WHITE], parapetHeightM: 0.9 },
    cerdaBlock: null,
  },
  'vila-antiga': {
    // PB+2/3 ≈ 10–14 m on small mixed plots; newer infill to PB+4/5.
    storeys: { min: 1, max: 6, default: 4 },
    groundFloorHeightM: 3.8,
    upperStoreyHeightM: 3.0,
    facadePalette: [
      [0.90, 0.85, 0.74], // cream
      [0.80, 0.64, 0.44], // ochre
      [0.74, 0.48, 0.36], // terracotta
      [0.92, 0.91, 0.87], // whitewash
      [0.86, 0.70, 0.62], // pale pink
      [0.66, 0.44, 0.32], // brick
      [0.74, 0.72, 0.68], // grey render
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: DARK_WOOD,
    windowWidthM: 1.0,
    bayM: 3.0,
    balcony: { probability: 0.75, depthM: 0.45 },
    attic: { probability: 0.2, setbackM: 2.5 },
    roof: { flatTerraceProbability: 0.7, tones: [TERRAT_TILE, ARAB_TILE, CEMENT_GREY], parapetHeightM: 0.9 },
    cerdaBlock: null,
  },
  'poblenou-industrial-22a': {
    // Brick factories 1–3 floors ("naus"), 22@ offices 6–12 floors (and a few towers).
    storeys: { min: 1, max: 12, default: 3 },
    groundFloorHeightM: 5.0, // industrial nave / office lobby
    upperStoreyHeightM: 3.6, // loft / office floor-to-floor
    facadePalette: [
      [0.62, 0.36, 0.26], // red factory brick
      [0.52, 0.30, 0.22], // dark brick
      [0.86, 0.80, 0.68], // cream render
      [0.66, 0.66, 0.64], // concrete
      [0.85, 0.87, 0.88], // white panel (22@)
      [0.30, 0.36, 0.40], // dark glass
      [0.78, 0.62, 0.44], // ochre
    ],
    shutterTone: VERD_PERSIANA, // residential blocks keep persianes
    windowFrameTone: [0.22, 0.23, 0.24], // steel factory windows
    windowWidthM: 1.8,
    bayM: 4.5, // brick pilaster rhythm of the naus
    balcony: { probability: 0.25, depthM: 0.6 },
    attic: { probability: 0.1, setbackM: 3 },
    roof: { flatTerraceProbability: 0.6, tones: [[0.62, 0.62, 0.60], ARAB_TILE, [0.30, 0.30, 0.30]], parapetHeightM: 0.8 },
    // Same Cerdà blocks; interiors are often whole-plot factory sheds.
    cerdaBlock: { buildableDepthM: 28, interiorGroundFloorHeightM: 5.5 },
  },
  'villa-residential': {
    // Torres PB+1/2 and low garden blocks up to PB+4/5.
    storeys: { min: 1, max: 6, default: 3 },
    groundFloorHeightM: 3.5,
    upperStoreyHeightM: 3.1,
    facadePalette: [
      [0.93, 0.92, 0.88], // white stucco
      [0.90, 0.85, 0.72], // cream
      [0.86, 0.74, 0.54], // pale ochre
      [0.88, 0.76, 0.68], // warm pink
      [0.76, 0.72, 0.64], // stone
      [0.78, 0.78, 0.76], // grey
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: [0.88, 0.88, 0.86],
    windowWidthM: 1.2,
    bayM: 3.5,
    balcony: { probability: 0.4, depthM: 1.2 }, // terraces rather than iron balconies
    attic: { probability: 0.2, setbackM: 3 },
    roof: { flatTerraceProbability: 0.45, tones: [ARAB_TILE, [0.32, 0.33, 0.35], CEMENT_GREY], parapetHeightM: 0.9 },
    cerdaBlock: null,
  },
  'zona-alta-apartments': {
    // Upper-class entre-mitgeres blocks PB+5/7 with setback àtics.
    storeys: { min: 4, max: 10, default: 7 },
    groundFloorHeightM: 4.0,
    upperStoreyHeightM: 3.0,
    facadePalette: [
      [0.92, 0.91, 0.88], // white
      [0.86, 0.81, 0.70], // cream stone
      [0.78, 0.78, 0.76], // pale grey
      [0.80, 0.68, 0.54], // beige brick
      [0.82, 0.70, 0.50], // ochre
      [0.84, 0.79, 0.68], // travertine cladding
    ],
    shutterTone: [0.46, 0.46, 0.42], // grey-green slatted / aluminium
    windowFrameTone: [0.24, 0.24, 0.24],
    windowWidthM: 1.6,
    bayM: 3.6,
    balcony: { probability: 0.7, depthM: 1.4 }, // deep (often glazed) terraces
    attic: { probability: 0.6, setbackM: 3 },
    roof: { flatTerraceProbability: 0.9, tones: [CEMENT_GREY, TERRAT_TILE, ROOF_WHITE], parapetHeightM: 1.0 },
    cerdaBlock: null,
  },
  'poligon-1960s': {
    // Open slab and tower blocks, typically PB+7 to PB+13.
    storeys: { min: 5, max: 16, default: 9 },
    groundFloorHeightM: 3.0,
    upperStoreyHeightM: 2.75, // minimum-standard housing of the era
    facadePalette: [
      [0.58, 0.38, 0.28], // brown-red brick
      [0.72, 0.54, 0.38], // ochre brick
      [0.82, 0.74, 0.60], // beige render
      [0.68, 0.67, 0.64], // grey
      [0.84, 0.78, 0.66], // cream
      [0.80, 0.79, 0.75], // dirty white
    ],
    shutterTone: ROLLER_BEIGE, // roller shutters
    windowFrameTone: ALUMINIUM,
    windowWidthM: 1.2,
    bayM: 3.0,
    balcony: { probability: 0.55, depthM: 1.0 }, // many closed as galeries
    attic: { probability: 0.05, setbackM: 2 },
    roof: { flatTerraceProbability: 0.95, tones: [CEMENT_GREY, ROOF_WHITE, TERRAT_TILE], parapetHeightM: 1.0 },
    cerdaBlock: null,
  },
  'hillside-selfbuilt': {
    // Self-built houses PB+1/3 stepping down steep slopes, some 1960s infill.
    storeys: { min: 1, max: 6, default: 3 },
    groundFloorHeightM: 3.0,
    upperStoreyHeightM: 2.8,
    facadePalette: [
      [0.64, 0.42, 0.32], // unrendered brick
      [0.72, 0.70, 0.66], // grey render
      [0.84, 0.78, 0.66], // cream
      [0.88, 0.86, 0.82], // white
      [0.76, 0.62, 0.44], // ochre
      [0.60, 0.60, 0.58], // concrete block
    ],
    shutterTone: ROLLER_BEIGE,
    windowFrameTone: ALUMINIUM,
    windowWidthM: 1.0,
    bayM: 3.0,
    balcony: { probability: 0.4, depthM: 0.8 },
    attic: { probability: 0.1, setbackM: 2 },
    roof: { flatTerraceProbability: 0.8, tones: [CEMENT_GREY, ARAB_TILE, TERRAT_TILE], parapetHeightM: 0.9 },
    cerdaBlock: null,
  },
  'modern-waterfront': {
    // Vila Olímpica blocks PB+6/8, Diagonal Mar / Fòrum towers; Hotel Arts & Mapfre ~44 storeys.
    storeys: { min: 4, max: 44, default: 10 },
    groundFloorHeightM: 5.0,
    upperStoreyHeightM: 3.4,
    facadePalette: [
      [0.90, 0.90, 0.88], // white concrete / panel
      [0.76, 0.78, 0.80], // light grey metal
      [0.46, 0.54, 0.60], // blue-grey glass
      [0.24, 0.30, 0.34], // dark glass
      [0.84, 0.78, 0.66], // sand stone cladding
      [0.72, 0.48, 0.36], // terracotta brick (Vila Olímpica)
    ],
    shutterTone: [0.56, 0.58, 0.60],
    windowFrameTone: [0.30, 0.32, 0.34],
    windowWidthM: 1.8,
    bayM: 3.6,
    balcony: { probability: 0.5, depthM: 1.8 }, // deep terraces
    attic: { probability: 0.1, setbackM: 3 },
    roof: { flatTerraceProbability: 1.0, tones: [ROOF_WHITE, CEMENT_GREY], parapetHeightM: 1.1 },
    cerdaBlock: null,
  },
  'hillside-park': {
    // Pavilions, museums, masies: few, low, generous floor heights.
    storeys: { min: 1, max: 4, default: 2 },
    groundFloorHeightM: 4.5,
    upperStoreyHeightM: 3.8,
    facadePalette: [
      [0.80, 0.72, 0.56], // Montjuïc sandstone
      [0.88, 0.84, 0.74], // cream
      [0.80, 0.64, 0.44], // ochre
      [0.92, 0.91, 0.88], // white
      [0.70, 0.68, 0.63], // stone grey
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: DARK_WOOD,
    windowWidthM: 1.4,
    bayM: 4.0,
    balcony: { probability: 0.15, depthM: 0.6 },
    attic: { probability: 0, setbackM: 0 },
    roof: { flatTerraceProbability: 0.4, tones: [ARAB_TILE, CEMENT_GREY], parapetHeightM: 0.9 },
    cerdaBlock: null,
  },
  'port-industrial': {
    // Warehouses and logistics sheds: tall single volumes, few openings.
    storeys: { min: 1, max: 4, default: 2 },
    groundFloorHeightM: 7.0,
    upperStoreyHeightM: 4.0,
    facadePalette: [
      [0.66, 0.68, 0.70], // corrugated steel
      [0.86, 0.87, 0.87], // white cladding
      [0.44, 0.52, 0.60], // blue-grey cladding
      [0.62, 0.62, 0.60], // precast concrete
      [0.56, 0.36, 0.26], // rust / brick
      [0.80, 0.74, 0.62], // sand panel
    ],
    shutterTone: [0.50, 0.52, 0.54],
    windowFrameTone: [0.40, 0.42, 0.44],
    windowWidthM: 2.4,
    bayM: 6.0, // portal-frame spacing
    balcony: { probability: 0, depthM: 0 },
    attic: { probability: 0, setbackM: 0 },
    roof: { flatTerraceProbability: 0.5, tones: [[0.56, 0.58, 0.60], ROOF_WHITE], parapetHeightM: 0.6 },
    cerdaBlock: null,
  },
  'mixed-urban': {
    // Dense 20th-c. entre-mitgeres infill, PB+4/6 ≈ 16–22 m.
    storeys: { min: 3, max: 9, default: 6 },
    groundFloorHeightM: 4.0,
    upperStoreyHeightM: 2.9,
    facadePalette: [
      [0.82, 0.74, 0.60], // beige
      [0.62, 0.40, 0.30], // brick
      [0.88, 0.82, 0.70], // cream
      [0.80, 0.64, 0.44], // ochre
      [0.72, 0.71, 0.68], // grey render
      [0.84, 0.66, 0.56], // salmon
      [0.88, 0.87, 0.84], // off-white
    ],
    shutterTone: VERD_PERSIANA,
    windowFrameTone: ALUMINIUM,
    windowWidthM: 1.2,
    bayM: 3.2,
    balcony: { probability: 0.7, depthM: 0.7 },
    attic: { probability: 0.25, setbackM: 3 },
    roof: { flatTerraceProbability: 0.9, tones: [TERRAT_TILE, CEMENT_GREY, ROOF_WHITE], parapetHeightM: 1.0 },
    cerdaBlock: null,
  },
}

export function typologyProfile(t: UrbanTypology): TypologyProfile {
  return TYPOLOGY_PROFILES[t]
}

// ── Lookup ─────────────────────────────────────────────────────────────────────

/** Is the point inside the municipality's bbox? A cheap prefilter, not a polygon test. */
export function isBarcelona(lat: number, lon: number): boolean {
  return lat >= BCN_BBOX[0] && lat <= BCN_BBOX[2] && lon >= BCN_BBOX[1] && lon <= BCN_BBOX[3]
}

export interface BarriHit {
  readonly barri: string
  readonly district: string
  readonly typology: UrbanTypology
  /** Official barri number 1..73. */
  readonly code: number
  /** Id of the TYPOLOGY_ZONES entry that overrode the barri's typology, if any. */
  readonly zone: string | null
}

interface DecodedBarri {
  readonly name: string
  readonly code: number
  readonly district: string
  /** Rings as interleaved [lat, lon, lat, lon, …] degrees. */
  readonly rings: readonly Float64Array[]
  readonly minLat: number
  readonly minLon: number
  readonly maxLat: number
  readonly maxLon: number
}

// Decoding the constant data is pure and deterministic; caching it is safe.
let decoded: readonly DecodedBarri[] | null = null

function decode(): readonly DecodedBarri[] {
  if (decoded) return decoded
  decoded = BCN_BARRIS.map((b) => {
    let minLat = Infinity, minLon = Infinity, maxLat = -Infinity, maxLon = -Infinity
    const rings = b.r.map((enc) => {
      const out = new Float64Array(enc.length)
      let la = 0, lo = 0
      for (let i = 0; i < enc.length; i += 2) {
        la += enc[i]; lo += enc[i + 1]
        const lat = la / 1e5, lon = lo / 1e5
        out[i] = lat; out[i + 1] = lon
        if (lat < minLat) minLat = lat
        if (lat > maxLat) maxLat = lat
        if (lon < minLon) minLon = lon
        if (lon > maxLon) maxLon = lon
      }
      return out
    })
    return { name: b.n, code: b.c, district: BCN_DISTRICTS[b.d], rings, minLat, minLon, maxLat, maxLon }
  })
  return decoded
}

/** Every barri's decoded rings as [lat, lon][] — for tests and debug overlays. */
export function barriRings(): { barri: string; district: string; rings: [number, number][][] }[] {
  return decode().map((b) => ({
    barri: b.name,
    district: b.district,
    rings: b.rings.map((r) => {
      const pts: [number, number][] = []
      for (let i = 0; i < r.length; i += 2) pts.push([r[i], r[i + 1]])
      return pts
    }),
  }))
}

/** Even-odd point-in-polygon over interleaved rings. */
function inRings(lat: number, lon: number, rings: readonly Float64Array[]): boolean {
  let inside = false
  for (const r of rings) {
    const n = r.length
    for (let i = 0, j = n - 2; i < n; j = i, i += 2) {
      const ay = r[i], ax = r[i + 1], by = r[j], bx = r[j + 1]
      if ((ay > lat) !== (by > lat) && lon < ((bx - ax) * (lat - ay)) / (by - ay) + ax) inside = !inside
    }
  }
  return inside
}

function inZone(lat: number, lon: number, ring: readonly (readonly [number, number])[]): boolean {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [ay, ax] = ring[i], [by, bx] = ring[j]
    if ((ay > lat) !== (by > lat) && lon < ((bx - ax) * (lat - ay)) / (by - ay) + ax) inside = !inside
  }
  return inside
}

/** Typology of a named barri (no zone overrides); 'mixed-urban' for an unknown name. */
export function barriTypology(barri: string): UrbanTypology {
  return BARRI_TYPOLOGY[barri] ?? 'mixed-urban'
}

/** Barri, district and typology at a point, or null outside Barcelona's barris. */
export function barriAt(lat: number, lon: number): BarriHit | null {
  if (!isBarcelona(lat, lon)) return null
  for (const b of decode()) {
    if (lat < b.minLat || lat > b.maxLat || lon < b.minLon || lon > b.maxLon) continue
    if (!inRings(lat, lon, b.rings)) continue
    let typology = barriTypology(b.name)
    let zone: string | null = null
    for (const z of TYPOLOGY_ZONES) {
      if (z.barris && !z.barris.includes(b.name)) continue
      if (inZone(lat, lon, z.ring)) { typology = z.typology; zone = z.id; break }
    }
    return { barri: b.name, district: b.district, typology, code: b.code, zone }
  }
  return null
}
