// ─── EbookView ────────────────────────────────────────────────────────────────
// /ebook and /ebook/<route> — the lead magnets: free PDF handbooks with a
// €19.99 sticker price, given away for an email address.
//
// One component, driven by the registry in src/lib/ebook.ts. Per-book copy
// (contents, selling points, FAQ) lives in COPY below, keyed by book id; the
// facts everyone quotes — page counts, paths, download filenames — come from the
// registry, which `npm run ebook` verifies against the rendered PDFs.
//
// The gate is deliberately soft. The address is posted to the Cloudflare Worker
// (→ Resend Audiences, see src/lib/subscribe.ts) and the download unlocks
// regardless of what the network says, because the PDF is a public static file
// anyway — pretending otherwise would be a dark pattern, and a broken worker
// must never cost a reader their download.
//
// English-only by design: the handbooks are English, so a localized shell
// around an English PDF would promise something the download does not keep.
//
// The static SEO shells for these routes are generated by
// scripts/seo/generate-ebook-page.ts (Book + FAQ JSON-LD) at build time.

import { useState, useEffect, useCallback, type FormEvent, type ReactNode } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import { useTranslation } from 'react-i18next'
import * as Icons from './Icons'
import SideRays from './reactbits/SideRays'
import { subscribeEmail } from '../lib/subscribe'
import { trackEmailCaptured, trackFeatureUsed } from '../lib/analytics'
import { RULE_COUNT } from '../types'
import { EBOOKS, PRIMARY_EBOOK, type EbookMeta } from '../lib/ebook'

const BASE = (import.meta.env.BASE_URL ?? '/') as string
const url = (file: string): string => `${BASE}${file}`.replace('//', '/')

/** Site path for a book's landing. */
export function ebookHref(book: EbookMeta): string {
  return url(book.route ? `ebook/${book.route}/` : 'ebook/')
}

// ── Per-book copy ─────────────────────────────────────────────────────────────

interface BookCopy {
  /** Short "what it is" line under the h1, after the subtitle. */
  positioning: string
  bullets:  ReactNode[]
  contents: { kicker: string; title: string; blurb: string }[]
  stats:    { value: string; label: string }[]
  honesty:  { title: string; body: string }[]
  honestyHeading: string
  honestyBody: ReactNode
  faqs: { q: string; a: string }[]
}

const COPY: Record<string, BookCopy> = {
  'ifc-delivery': {
    positioning: 'written for the person who has to press Upload and put their name next to the file',
    bullets: [
      <>All <strong className="font-semibold text-[var(--text)]">{RULE_COUNT} checks</strong> documented one by one — cause, consequence, and the exact fix in Revit, ArchiCAD, Tekla and Allplan.</>,
      <>The <strong className="font-semibold text-[var(--text)]">Health Score formula in full</strong>, weights included, so you can reproduce it or argue with it.</>,
      <><strong className="font-semibold text-[var(--text)]">Four BEP clauses and two emails</strong> you can paste into a project today.</>,
      <>A pre-delivery checklist that fits on a page, and a glossary that does not read like a standard.</>,
    ],
    contents: [
      { kicker: 'Chapter 1', title: 'Why good models get rejected', blurb: 'The acceptance gap, the three failure modes, and why “it opens fine” is not a check.' },
      { kicker: 'Chapter 2', title: 'What “delivered” actually means', blurb: 'ISO 19650 information containers, suitability, and level of information need — in working terms.' },
      { kicker: 'Chapter 3', title: 'The pre-flight check', blurb: 'The eight categories, the Health Score formula in full, and the coverage trap that makes clean reports lie.' },
      { kicker: 'Chapter 4', title: `The ${RULE_COUNT}-check reference`, blurb: 'Every check, one by one: what it tests, why it matters, and how to fix it in four authoring tools.' },
      { kicker: 'Chapter 5', title: 'The delivery workflow', blurb: 'Seven repeatable steps, the run diff, and what only shows up once models are federated.' },
      { kicker: 'Chapter 6', title: 'The evidence pack', blurb: 'Report, check record, BCF, COBie and the six-line transmittal note that prevents most disputes.' },
      { kicker: 'Chapter 7', title: 'The contract layer', blurb: 'Four BEP clauses, an acceptance criteria table and two emails — written to be copied.' },
      { kicker: 'Appendices', title: 'Checklist, index, glossary', blurb: 'The pre-delivery checklist, all checks indexed by identifier, and where the settings live per tool.' },
    ],
    stats: [
      { value: String(RULE_COUNT), label: 'checks, one by one' },
      { value: '4', label: 'authoring tools' },
      { value: '7', label: 'clauses & templates' },
    ],
    honestyHeading: 'Generated from a working validator',
    honestyBody: (
      <>
        The {RULE_COUNT}-check reference, the score weights and the tool-by-tool fixes are not retyped
        into the book — they are generated from the source of the validator that runs at
        ifcvieweronline.eu. Add a check to the product and the handbook regenerates with it.
      </>
    ),
    honesty: [
      { title: 'No invented statistics', body: 'Where a number appears it is either arithmetic you can redo yourself or a value taken from the tool. There is no “studies show that 73% of BIM projects…”.' },
      { title: 'No product tour', body: 'The checks are statements about IFC files, reproducible in any checker. The book tells you what to look for, not which button to press.' },
      { title: 'Written to be copied', body: 'The clauses, the acceptance table, the checklist and the emails are yours to adapt on your own projects, without attribution.' },
    ],
    faqs: [
      { q: 'Is it really free?', a: 'Yes. No card, no account, no trial. It is priced at €19.99 because that is what a handbook this size sells for; it is given away because a BIM coordinator who checks their models before delivery is exactly the person our validator is built for.' },
      { q: 'What do you do with my email?', a: 'It goes to our mailing list so we can send you the handbook and, occasionally, new guides. No sharing, no reselling, unsubscribe in one click. The download is not conditional on staying subscribed.' },
      { q: 'Do I need to use your tool to apply it?', a: 'No. Every check in the reference is a statement about an IFC file, not about a product — reproducible in any checker. Our validator happens to be free and to run in your browser, which makes it convenient rather than necessary.' },
      { q: 'Which authoring tools does it cover?', a: 'The fix for each check is written out for Revit, ArchiCAD, Tekla Structures and Allplan. The underlying cause is described tool-independently, so the reasoning transfers to any exporter.' },
    ],
  },

  'bim-information': {
    positioning: 'written for whoever ended up responsible for making the information side of a project work',
    bullets: [
      <>How a <strong className="font-semibold text-[var(--text)]">common data environment</strong> actually works: the four states, what each one promises, and the two transitions that carry all the risk.</>,
      <>The <strong className="font-semibold text-[var(--text)]">OIR → AIR → PIR → EIR → BEP</strong> chain, explained by what each document is for — and where it usually breaks.</>,
      <><strong className="font-semibold text-[var(--text)]">Level of information need</strong> without the LOD argument: why the numbers fail, and a specification table two teams would read the same way.</>,
      <>Six clauses and templates, a project set-up checklist, and a glossary written the way projects use the words.</>,
    ],
    contents: [
      { kicker: 'Chapter 1', title: 'What BIM is, once the marketing stops', blurb: 'Why the 3D framing causes so much damage, and the three things that actually have to work.' },
      { kicker: 'Chapter 2', title: 'The common data environment', blurb: 'Information containers, the four states, suitability codes, naming, and how to choose a platform.' },
      { kicker: 'Chapter 3', title: 'The requirement chain', blurb: 'OIR, AIR, PIR, EIR, BEP — what each is for, where the chain breaks, and how to write an EIR that can be met.' },
      { kicker: 'Chapter 4', title: 'Level of information need', blurb: 'The LOD mess untangled, and a specification table that two teams would interpret the same way.' },
      { kicker: 'Chapter 5', title: 'Planning the delivery', blurb: 'TIDP and MIDP, milestones tied to decisions, and the responsibility matrix.' },
      { kicker: 'Chapter 6', title: 'Who is responsible for what', blurb: 'Appointing, lead appointed and appointed parties — and the competence questions worth asking.' },
      { kicker: 'Chapter 7', title: 'Running the CDE day to day', blurb: 'The weekly rhythm, six rules worth writing on the wall, and the failure modes with their real causes.' },
      { kicker: 'Chapter 8', title: 'Federation and coordination', blurb: 'The four agreements federation depends on, the coordination cycle, and why triage is the skill.' },
      { kicker: 'Chapter 9', title: 'Quality gates', blurb: 'Three gates, what to check at each, acceptance criteria, and the check nobody runs on the checker.' },
      { kicker: 'Chapter 10', title: 'Handover: project to asset', blurb: 'PIM to AIM, why handover data is usually bad, and the test you can run in year one.' },
      { kicker: 'Chapter 11', title: 'What to do first', blurb: 'The order that works when you have limited authority and a live project — and what not to do first.' },
      { kicker: 'Appendices', title: 'Checklist, templates, glossary', blurb: 'Project set-up checklist, six clauses and emails to adapt, and where to go next.' },
    ],
    stats: [
      { value: '4',  label: 'CDE states, explained' },
      { value: '5',  label: 'requirement documents' },
      { value: '6',  label: 'clauses & emails' },
    ],
    honestyHeading: 'Written from practice, not from the standard',
    honestyBody: (
      <>
        This is not a summary of ISO 19650. It explains what the machinery does and what to do on
        Monday — because information management rarely fails from misreading a clause. It fails
        because nobody could see what the clause was for.
      </>
    ),
    honesty: [
      { title: 'Standards named, never faked', body: 'Referenced by name and part — ISO 19650-2, EN 17412-1 — never by an invented clause number. Where a convention is national rather than international, it says so.' },
      { title: 'Tool-agnostic on purpose', body: 'No software menus. Which authoring tool you use is your business; how information crosses between organisations is the subject.' },
      { title: 'Doable on a live project', body: 'Everything here can be started mid-project by somebody who does not control the budget. Chapter 11 is the order to do it in.' },
    ],
    faqs: [
      { q: 'Is it really free?', a: 'Yes. No card, no account, no trial. It is priced at €19.99 because that is what a handbook this size sells for; it is given away because the people who run information properly are the people our validator is built for.' },
      { q: 'Does this replace reading ISO 19650?', a: 'No, and it says so. Buy the standard — its normative wording matters when things go legal. This handbook explains what the machinery does in operational terms, which the standard deliberately does not.' },
      { q: 'Is it tied to any software?', a: 'No. There are no product menus in it. It covers the process: the CDE, the requirement chain, level of information need, delivery planning, federation, quality gates and handover.' },
      { q: 'I only work on small projects. Is it relevant?', a: 'Chapter 11 exists for exactly that. The full apparatus is for large projects; the first four steps in that chapter are worth doing on a project of any size, and most of them take an afternoon.' },
    ],
  },
}

// ── Small building blocks ─────────────────────────────────────────────────────

function Stat({ value, label }: { value: string; label: string }) {
  return (
    <div>
      <p className="font-serif text-[30px] leading-none text-[var(--text)]">{value}</p>
      <p className="mt-1.5 text-[11.5px] leading-snug text-[var(--text-faint)]">{label}</p>
    </div>
  )
}

function Bullet({ children }: { children: ReactNode }) {
  return (
    <li className="flex gap-2.5 text-[13.5px] leading-relaxed text-[var(--text-dim)]">
      <Icons.Check size={15} className="mt-[3px] flex-none text-[var(--accent-2)]" aria-hidden="true" />
      <span>{children}</span>
    </li>
  )
}

// ── Email gate ────────────────────────────────────────────────────────────────

type GateState = 'idle' | 'sending' | 'done'

function EmailGate({ id, book, compact = false }: { id: string; book: EbookMeta; compact?: boolean }) {
  const [email, setEmail]   = useState('')
  const [state, setState]   = useState<GateState>('idle')
  const [notice, setNotice] = useState<string | null>(null)

  const download = useCallback((): void => {
    trackFeatureUsed({ feature: 'ebook_download' })
    const a = document.createElement('a')
    a.href = url(book.pdfFile)
    a.download = book.filename
    document.body.appendChild(a)
    a.click()
    a.remove()
  }, [book])

  const onSubmit = useCallback(async (e: FormEvent): Promise<void> => {
    e.preventDefault()
    const value = email.trim()
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(value)) {
      setNotice('That address does not look right — check it and try again.')
      return
    }
    setNotice(null)
    setState('sending')

    const locale = (typeof navigator !== 'undefined' ? navigator.language : 'en').slice(0, 2)
    const result = await subscribeEmail(value, book.subscribeSource, locale)

    if (result.ok) {
      trackEmailCaptured({ source: book.subscribeSource, already_subscribed: !!result.already, locale })
    } else if (!result.disabled) {
      // The list is unreachable. Say so plainly — and hand over the book anyway.
      setNotice('We could not reach our mailing list just now, so you may not hear from us. Your download is ready regardless.')
    }

    setState('done')
    download()
  }, [email, download, book])

  if (state === 'done') {
    return (
      <div
        className="rounded-2xl border px-5 py-5"
        style={{ borderColor: 'var(--border)', background: 'var(--surface-2)' }}
      >
        <p className="flex items-center gap-2 text-[14px] font-semibold text-[var(--text)]">
          <Icons.OK size={17} className="text-[var(--ok)]" aria-hidden="true" />
          Your download has started
        </p>
        <p className="mt-1.5 text-[12.5px] leading-relaxed text-[var(--text-dim)]">
          {notice ?? 'If nothing happened, your browser may have blocked it — use the direct link below.'}
        </p>
        <button
          type="button"
          onClick={download}
          className="mt-3 inline-flex items-center gap-2 rounded-lg border px-3.5 py-2 text-[12.5px] font-medium text-[var(--text)] transition-colors hover:border-[var(--accent)]"
          style={{ borderColor: 'var(--border-strong)', background: 'var(--surface)' }}
        >
          <Icons.Download size={14} aria-hidden="true" />
          Download the PDF again
        </button>
      </div>
    )
  }

  return (
    <form onSubmit={onSubmit} className={compact ? '' : 'mt-7'}>
      <div className="flex flex-col gap-2.5 sm:flex-row">
        <label htmlFor={id} className="sr-only">Your email address</label>
        <input
          id={id}
          type="email"
          required
          autoComplete="email"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="you@practice.com"
          className="flex-1 rounded-xl border px-4 py-3 text-[14px] text-[var(--text)] outline-none transition-colors placeholder:text-[var(--text-faint)] focus:border-[var(--accent)]"
          style={{ borderColor: 'var(--border-strong)', background: 'var(--surface)' }}
        />
        <button
          type="submit"
          disabled={state === 'sending'}
          className="inline-flex items-center justify-center gap-2 rounded-xl px-5 py-3 text-[14px] font-semibold text-white transition-opacity disabled:opacity-60"
          style={{ background: 'var(--accent)' }}
        >
          <Icons.Download size={15} aria-hidden="true" />
          {state === 'sending' ? 'Sending…' : 'Send me the handbook'}
        </button>
      </div>
      <p className="mt-2.5 text-[11.5px] leading-relaxed text-[var(--text-faint)]">
        {notice ?? (
          <>No account, no card. One email, unsubscribe any time — see the{' '}
            <a href={url('privacy')} className="underline decoration-[var(--border-strong)] underline-offset-2 hover:text-[var(--text-dim)]">privacy policy</a>.
          </>
        )}
      </p>
    </form>
  )
}

// ── The other book ────────────────────────────────────────────────────────────

function CompanionCard({ book }: { book: EbookMeta }) {
  return (
    <a
      href={ebookHref(book)}
      className="flex flex-col items-start gap-5 rounded-2xl border p-5 transition-colors hover:border-[var(--accent)] sm:flex-row sm:items-center sm:gap-6 sm:p-6"
      style={{ borderColor: 'var(--border)', background: 'var(--surface-2)' }}
    >
      <img
        src={url(book.coverFile)}
        alt={`Cover of ${book.title}`}
        width={794}
        height={1123}
        loading="lazy"
        className="w-[70px] shrink-0 rounded-md sm:w-[84px]"
        style={{ boxShadow: '0 12px 26px -12px rgba(0,0,0,.7), 0 0 0 1px rgba(255,255,255,.06)' }}
      />
      <div className="min-w-0 flex-1">
        <p className="text-[10.5px] font-medium uppercase tracking-[0.14em] text-[var(--accent-2)]">
          Also free · {book.pages} pages
        </p>
        <p className="mt-1 text-[16px] font-semibold tracking-tight text-[var(--text)]">{book.title}</p>
        <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--text-dim)]">{book.blurb}</p>
      </div>
      <span className="inline-flex shrink-0 items-center gap-1.5 rounded-[8px] px-3.5 h-[32px] text-[12.5px] font-semibold text-white" style={{ background: 'var(--accent)' }}>
        Get it free
        <Icons.ArrowRight size={12} aria-hidden="true" />
      </span>
    </a>
  )
}

// ── Page ──────────────────────────────────────────────────────────────────────

interface EbookViewProps {
  onNavigateToLanding: () => void
  /** Which handbook to show. Defaults to the primary one at /ebook/. */
  book?: EbookMeta
}

export default function EbookView({ onNavigateToLanding, book = PRIMARY_EBOOK }: EbookViewProps) {
  const reduced = useReducedMotion()
  const copy    = COPY[book.id] ?? COPY[PRIMARY_EBOOK.id]
  const others  = EBOOKS.filter(b => b.id !== book.id)

  // `i18n.language` is in the deps on purpose: App's useSeo rewrites
  // document.title whenever the detected locale settles, which can land after
  // this lazily-loaded view has mounted. Re-applying keeps the tab honest.
  const { i18n } = useTranslation()
  useEffect(() => {
    const prev = document.title
    document.title = `${book.title} — free ${book.pages}-page PDF · IFC Viewer Online`
    return () => { document.title = prev }
  }, [book, i18n.language])

  return (
    <div className="min-h-screen flex flex-col" style={{ background: 'var(--bg)', color: 'var(--text)', position: 'relative' }}>
      <div className="absolute left-0 right-0 top-0 pointer-events-none hidden sm:block" style={{ height: '70vh', zIndex: 0 }} aria-hidden="true">
        <SideRays
          speed={0.6} rayColor1="#5E6AD2" rayColor2="#8B93E8" intensity={0.65}
          spread={1.1} origin="top-right" saturation={1.0} blend={0.5} falloff={2.8} opacity={0.22}
        />
      </div>

      {/* ── Header ── */}
      <header
        className="border-b border-[var(--border)] px-4 sm:px-7 py-4 flex items-center gap-3 sticky top-0 z-10"
        style={{ background: 'var(--bg)', position: 'relative' }}
      >
        <button onClick={onNavigateToLanding} className="flex items-center gap-2 text-[var(--text-dim)] hover:text-[var(--text)] transition-colors">
          <Icons.Logo size={18} aria-hidden="true" />
          <span className="text-[13px] font-semibold tracking-tight">IFC Viewer Online</span>
        </button>
        <a
          href={url('blog/')}
          className="ml-auto text-[12px] text-[var(--text-dim)] hover:text-[var(--text)] transition-colors"
        >
          Blog
        </a>
      </header>

      <main className="flex-1" style={{ position: 'relative', zIndex: 1 }}>

        {/* ── Hero ── */}
        <section className="px-4 sm:px-7 pt-12 pb-16 sm:pt-20 sm:pb-24">
          <div className="mx-auto grid max-w-5xl gap-12 lg:grid-cols-[1fr_minmax(0,340px)] lg:items-start lg:gap-16">
            <div>
              <p className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-[11px] font-medium tracking-wide"
                 style={{ borderColor: 'var(--border-strong)', background: 'var(--surface)', color: 'var(--accent-2)' }}>
                Free download
                <span className="text-[var(--text-faint)]">·</span>
                <span className="text-[var(--text-faint)] line-through">{book.retail}</span>
              </p>
              <h1 className="mt-5 font-serif text-[40px] leading-[1.04] tracking-tight sm:text-[54px]">
                {book.title}
              </h1>
              <p className="mt-4 max-w-xl text-[16px] leading-relaxed text-[var(--text-dim)]">
                {book.subtitle}. {book.pages} pages, {copy.positioning}.
              </p>

              <ul className="mt-7 space-y-2.5">
                {copy.bullets.map((b, i) => <Bullet key={i}>{b}</Bullet>)}
              </ul>

              <EmailGate id={`ebook-email-hero-${book.id}`} book={book} />

              <div className="mt-10 flex flex-wrap gap-x-12 gap-y-6 border-t pt-7" style={{ borderColor: 'var(--border)' }}>
                <Stat value={String(book.pages)} label="pages, PDF" />
                {copy.stats.map(s => <Stat key={s.label} value={s.value} label={s.label} />)}
              </div>
            </div>

            {/* Cover — the real one, rendered from the book's own source */}
            <motion.div
              initial={reduced ? false : { opacity: 0, y: 14 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, ease: 'easeOut' }}
              className="mx-auto w-full max-w-[300px] lg:sticky lg:top-24"
            >
              <img
                src={url(book.coverFile)}
                alt={`Cover of ${book.title}`}
                width={794}
                height={1123}
                className="w-full rounded-lg"
                style={{ boxShadow: '0 30px 60px -20px rgba(0,0,0,.7), 0 0 0 1px rgba(255,255,255,.06)' }}
              />
              <p className="mt-4 text-center text-[11.5px] text-[var(--text-faint)]">
                PDF · {book.pages} pages · English · no DRM
              </p>
            </motion.div>
          </div>
        </section>

        {/* ── What's inside ── */}
        <section className="border-t px-4 sm:px-7 py-16 sm:py-20" style={{ borderColor: 'var(--border)' }}>
          <div className="mx-auto max-w-5xl">
            <h2 className="font-serif text-[30px] tracking-tight sm:text-[36px]">What is inside</h2>
            <div className="mt-10 grid gap-x-10 gap-y-7 sm:grid-cols-2">
              {copy.contents.map((c) => (
                <div key={c.title} className="border-t pt-4" style={{ borderColor: 'var(--border)' }}>
                  <p className="text-[10.5px] font-medium uppercase tracking-[.14em] text-[var(--accent-2)]">{c.kicker}</p>
                  <p className="mt-1.5 text-[15px] font-semibold text-[var(--text)]">{c.title}</p>
                  <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--text-dim)]">{c.blurb}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── Why it is honest ── */}
        <section className="border-t px-4 sm:px-7 py-16 sm:py-20" style={{ borderColor: 'var(--border)' }}>
          <div className="mx-auto grid max-w-5xl gap-10 lg:grid-cols-2 lg:gap-16">
            <div>
              <h2 className="font-serif text-[30px] tracking-tight sm:text-[36px]">{copy.honestyHeading}</h2>
              <p className="mt-4 text-[14px] leading-relaxed text-[var(--text-dim)]">{copy.honestyBody}</p>
            </div>
            <div className="space-y-4">
              {copy.honesty.map((h) => (
                <div key={h.title} className="rounded-xl border px-5 py-4" style={{ borderColor: 'var(--border)', background: 'var(--surface-2)' }}>
                  <p className="text-[13.5px] font-semibold text-[var(--text)]">{h.title}</p>
                  <p className="mt-1.5 text-[12.5px] leading-relaxed text-[var(--text-dim)]">{h.body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── The other handbook ── */}
        {others.length > 0 && (
          <section className="border-t px-4 sm:px-7 py-16 sm:py-20" style={{ borderColor: 'var(--border)' }}>
            <div className="mx-auto max-w-5xl">
              <h2 className="font-serif text-[30px] tracking-tight sm:text-[36px]">The companion volume</h2>
              <p className="mt-3 max-w-2xl text-[14px] leading-relaxed text-[var(--text-dim)]">
                Two handbooks, one argument split at the file boundary: one about the information process
                around a project, one about the model that has to survive it.
              </p>
              <div className="mt-8 space-y-4">
                {others.map(b => <CompanionCard key={b.id} book={b} />)}
              </div>
            </div>
          </section>
        )}

        {/* ── FAQ ── */}
        <section className="border-t px-4 sm:px-7 py-16 sm:py-20" style={{ borderColor: 'var(--border)' }}>
          <div className="mx-auto max-w-3xl">
            <h2 className="font-serif text-[30px] tracking-tight sm:text-[36px]">Questions</h2>
            <dl className="mt-8 space-y-6">
              {copy.faqs.map((f) => (
                <div key={f.q} className="border-t pt-5" style={{ borderColor: 'var(--border)' }}>
                  <dt className="text-[14.5px] font-semibold text-[var(--text)]">{f.q}</dt>
                  <dd className="mt-2 text-[13.5px] leading-relaxed text-[var(--text-dim)]">{f.a}</dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        {/* ── Closing CTA ── */}
        <section className="border-t px-4 sm:px-7 py-16 sm:py-20" style={{ borderColor: 'var(--border)' }}>
          <div className="mx-auto max-w-2xl text-center">
            <h2 className="font-serif text-[30px] tracking-tight sm:text-[38px]">Get the handbook</h2>
            <p className="mx-auto mt-3 max-w-lg text-[14px] leading-relaxed text-[var(--text-dim)]">
              {book.pages} pages, free, no account. If it saves you one rejected delivery it has paid for
              itself several times over.
            </p>
            <div className="mx-auto mt-7 max-w-xl text-left">
              <EmailGate id={`ebook-email-footer-${book.id}`} book={book} compact />
            </div>
            <p className="mt-8 text-[12.5px] text-[var(--text-faint)]">
              Prefer to try the tool first?{' '}
              <button onClick={onNavigateToLanding} className="underline decoration-[var(--border-strong)] underline-offset-2 hover:text-[var(--text-dim)]">
                Validate an IFC file in your browser
              </button>
              {' '}— it is free too, and nothing is uploaded.
            </p>
          </div>
        </section>
      </main>

      <footer className="border-t border-[var(--border)] px-4 sm:px-7 py-5 text-[11px] text-[var(--text-faint)]">
        <div className="mx-auto flex max-w-5xl flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <span>© 2026 IFC Viewer Online</span>
          <span className="flex gap-4">
            <a href={url('blog/')} className="hover:text-[var(--text)] transition-colors">Blog</a>
            <a href={url('privacy')} className="hover:text-[var(--text)] transition-colors">Privacy</a>
            <button onClick={onNavigateToLanding} className="hover:text-[var(--text)] transition-colors bg-transparent border-0 p-0 cursor-pointer">
              ← Back to home
            </button>
          </span>
        </div>
      </footer>
    </div>
  )
}
