// ─── city-search ──────────────────────────────────────────────────────────────
// Offline city search over the bundled GeoNames dataset (cities.json,
// generated by scripts/solar/build-cities.mjs — CC BY 4.0, attribution shown
// in the UI). 100 % local: no geocoding API ever sees the project's location.
//
// The dataset is population-sorted, so array order IS the ranking: the search
// walks it once, preferring prefix matches over substring matches, both in
// population order. Diacritics are stripped on both sides ("málaga" ≡
// "Malaga"). Known v1 limitation: only the primary (mostly Latin) name is
// indexed — native-script queries (東京, Москва) won't match.

export interface City {
  name: string
  country: string
  lat: number
  lon: number
}

export interface SearchableCity extends City {
  /** Precomputed normalized name (lowercase, diacritic-free). */
  norm: string
}

type CityTuple = [name: string, country: string, lat: number, lon: number]

export function normalizeCityQuery(s: string): string {
  return s.normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase().trim()
}

/**
 * Pure search (DI-friendly for tests): prefix matches first, then substring
 * matches, both in dataset (= population) order.
 */
export function searchCities(query: string, cities: readonly SearchableCity[], limit = 8): City[] {
  const q = normalizeCityQuery(query)
  if (q.length < 2) return []
  const prefix: City[] = []
  const substr: City[] = []
  for (const c of cities) {
    if (c.norm.startsWith(q)) {
      prefix.push(c)
      if (prefix.length >= limit) break
    } else if (substr.length < limit && c.norm.includes(q)) {
      substr.push(c)
    }
  }
  return prefix.concat(substr).slice(0, limit)
}

// ── Lazy dataset loader (own chunk — fetched on first search only) ─────────────

let citiesPromise: Promise<SearchableCity[]> | null = null

export function loadCities(): Promise<SearchableCity[]> {
  citiesPromise ??= import('./cities.json').then((m) => {
    const tuples = (m.default as unknown as { cities: CityTuple[] }).cities
    return tuples.map(([name, country, lat, lon]) => ({
      name, country, lat, lon,
      norm: normalizeCityQuery(name),
    }))
  })
  return citiesPromise
}
